/* QP_CONVERSA · fluency2 (gerado em 17/09/2026). O "Agora vocês" do modo
 * professor: uma proposta em duplas por ponto gramatical. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['fluency2'] = {
  'One / A / An': { q: 'Ask your partner if they have certain things with them (a charger, an umbrella). Answer with one: Yes, I have one.', apoio: [] },
  'Reporting Verbs – Time Changes': { q: 'Tell your partner what someone told you last week about their plans, changing the time words (the next day, that week).', apoio: [] },
  'Reported Questions – Yes/No': { q: 'Tell your partner some yes/no questions people asked you this week. Report them with asked me if.', apoio: [] },
  'Reported Questions – Wh-': { q: 'Tell your partner what a teacher, relative or friend asked you recently. Report the questions.', apoio: [] },
  'Past Perfect Continuous': { q: 'Tell your partner about a time you were very tired. What had you been doing all day?', apoio: [] },
  'So / Neither': { q: 'Say three things about your tastes and habits. Your partner agrees with So do I or Neither do I when it is true.', apoio: [] },
  'Wish + Past Perfect': { q: 'Tell your partner about a small thing you wish you had done differently last year.', apoio: [] },
  'Verbs with Two Objects': { q: 'Tell your partner about a gift you gave someone, and who taught you something important.', apoio: [] },
  'Possessive Before -ing': { q: 'Tell your partner about a habit of a friend or relative that you don\'t mind, and one that bothers you. Use their + -ing.', apoio: [] },
  'Indirect Questions': { q: 'You are a tourist in your partner\'s city. Ask politely: Could you tell me where...? Do you know if...?', apoio: [] },
  'Reported Questions': { q: 'Interview your partner with three questions. Then report their answers to another pair.', apoio: [] },
  'So / Neither – Disagreement': { q: 'Say three opinions or habits. Your partner disagrees when it is true: I don\'t. / I do.', apoio: [] },
  'Reporting Verbs': { q: 'Tell your partner about advice someone gave you. Use advised, suggested, promised or reminded.', apoio: [] },
  'Wish + Would': { q: 'Tell your partner three things you wish people around you would do or stop doing.', apoio: [] },
  'So / Such': { q: 'Describe the best concert, trip or meal you have had using so and such.', apoio: [] },
  'Future Perfect': { q: 'Tell your partner three things you will have done by the end of this year.', apoio: [] },
  'Whose (Relative)': { q: 'Describe a person you admire whose work or story inspires you.', apoio: [] },
  'Defining vs Non-Defining Clauses': { q: 'Tell your partner about your hometown, which..., and about a place where you like to spend time.', apoio: [] },
  'Verbs of Opinion': { q: 'Give your opinion on social media for teenagers. Use I believe, I doubt, I suppose.', apoio: [] },
  'Order of Adverbs': { q: 'Tell your partner what you did yesterday: how, where and when. Put the adverbs in order.', apoio: [] },
  'See/Hear + Verb or -ing': { q: 'Tell your partner what you saw or heard people doing on your way to class today.', apoio: [] },
  'Be / Get Used To': { q: 'Tell your partner something that was hard to get used to (a new school, job or routine) and something you are used to now.', apoio: [] },
  'Whatever / Whenever / Wherever / However': { q: 'Tell your partner what you would do on a perfect day off: whatever, wherever and whenever you want.', apoio: [] },
  'Uncountable Nouns': { q: 'Ask your partner for advice and information about a trip. Use a piece of advice and some information.', apoio: [] },
  'Phrasal Verbs – Reinvention': { q: 'Tell your partner about a plan that was called off and an idea you held on to even when it was hard.', apoio: [] },
  'Phrasal Verbs – Animals': { q: 'Tell your partner about a time you chickened out of something, and who horses around in your family or class.', apoio: [] },
  'Phrasal Verbs – Regrets': { q: 'Tell your partner where you were brought up and a problem you had to figure out on your own.', apoio: [] },
  'Phrasal Verbs – Learning': { q: 'Tell your partner what you do to catch up with a class you missed and what you go over before a test.', apoio: [] },
  'Phrasal Verbs – Careers': { q: 'Tell your partner what you do so you don\'t burn out, and about a plan that fell through.', apoio: [] },
  'Phrasal Verbs – Leisure': { q: 'Tell your partner what helps you loosen up after a busy day and what holds you back from trying new hobbies.', apoio: [] },
  'Phrasal Verbs – Art': { q: 'Tell your partner about a story you made up as a kid and a book or comic you pored over.', apoio: [] },
  'Phrasal Verbs – Communication': { q: 'Tell your partner who you open up to easily and how you feel when someone cuts you off.', apoio: [] },
  'Phrasal Verbs – Crime': { q: 'Tell your partner about a movie or series where someone broke into a place or got away with something. How did it end?', apoio: [] },
  'Phrasal Verbs – Caring': { q: 'Tell your partner about a time friends or neighbors pitched in to help, or dropped by without calling.', apoio: [] }
};
