/* QP_CONVERSA · infocus (gerado em 17/09/2026). O "Agora vocês" do modo
 * professor: uma proposta em duplas por ponto gramatical. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['infocus'] = {
  'Present Tenses': { q: 'Tell your partner what you usually do on weekdays and what you are working on these days.', apoio: [] },
  'Past Tenses': { q: 'Tell your partner about a memorable school day: what was happening and what had happened before.', apoio: [] },
  'Future Tenses': { q: 'Tell your partner your plans for next year and one prediction about your city.', apoio: [] },
  'Subjunctive – That-Clauses': { q: 'Tell your partner what you suggest that a new student do to learn English faster. Use suggest that, it is essential that.', apoio: [] },
  'First Conditional': { q: 'Tell your partner what you will do if you get a free afternoon this week.', apoio: [] },
  'Second Conditional': { q: 'Ask your partner: If you could change one thing about your school or job, what would it be?', apoio: [] },
  'Third Conditional': { q: 'Tell your partner about a choice from the past: what would have happened if you had chosen differently?', apoio: [] },
  'Mixed Conditionals': { q: 'Tell your partner: If you had grown up in another country, how would your life be different today?', apoio: [] },
  'Conditionals – Unless/As Long As': { q: 'Tell your partner your rules for lending things to friends. Use as long as and unless.', apoio: [] },
  'Present Tenses – State Verbs': { q: 'Tell your partner what you believe, prefer and own when it comes to technology.', apoio: [] },
  'Past Tenses – While/When': { q: 'Tell your partner about something funny that happened while you were traveling or studying.', apoio: [] },
  'Future Tenses – Future Perfect': { q: 'Tell your partner three things you will have achieved in five years.', apoio: [] },
  'Conditionals – Formal Inversion': { q: 'Give your partner formal advice for a job interview. Use Should you..., Had I known..., Were I you...', apoio: [] },
  'Used To / Be Used To': { q: 'Tell your partner what you used to do as a child and something you are used to doing now.', apoio: [] },
  'Future Continuous': { q: 'Tell your partner what you will be doing this time tomorrow and this time next year.', apoio: [] },
  'Compound Adjectives': { q: 'Describe a friend, a place and a movie using compound adjectives like easy-going, well-known or eco-friendly.', apoio: [] },
  'Emphatic Forms – Do/Does/Did': { q: 'Tell your partner something you do enjoy, even if it surprises people, and something you did do last week despite being tired.', apoio: [] },
  'Reflexive and Intensive Pronouns': { q: 'Tell your partner something you made yourself and something you learned by yourself.', apoio: [] },
  'Subjunctive – Wish / If + Were': { q: 'Tell your partner: If you were the principal of your school for a day, what would you change? What do you wish were different?', apoio: [] },
  'Nouns + Particles': { q: 'Tell your partner about a recent workout, a breakdown in your routine or a comeback you admire.', apoio: [] },
  'Zero Conditional': { q: 'Tell your partner what always happens to you if you skip breakfast or sleep late.', apoio: [] },
  'Inversion – Negative Adverbials': { q: 'Tell your partner about an amazing experience. Start with Never have I... or Rarely do I...', apoio: [] },
  'Inversion': { q: 'Describe the best view you have seen, starting with Not only... or Little did I know...', apoio: [] },
  'Gerunds vs Infinitives – Meaning Change': { q: 'Tell your partner something you remember doing as a child and something you must remember to do this week.', apoio: [] },
  'Gerunds vs Infinitives': { q: 'Tell your partner an activity you enjoy doing, one you plan to do and one you avoid doing.', apoio: [] },
  'Relative Pronouns – Advanced': { q: 'Describe a place in which you feel relaxed and a person to whom you would give advice.', apoio: [] },
  'Passive Voice – All Tenses': { q: 'Tell your partner how your school or city has been changed in recent years and what will be built next.', apoio: [] },
  'Passive Voice – Modal': { q: 'Tell your partner three things that should be done to improve your neighborhood.', apoio: [] },
  'Cleft Sentences – It Is...That': { q: 'Tell your partner who or what made you start studying English. Use It was ... that ...', apoio: [] },
  'Cleft Sentences – What': { q: 'Tell your partner what you love most about weekends and what you need right now. Start with What I...', apoio: [] },
  'Comparatives/Superlatives – Advanced': { q: 'Compare two phones, cities or sports using by far, slightly, the least and much more.', apoio: [] },
  'Comparatives – Modification': { q: 'Compare your life now and five years ago using a bit, far, a lot and nowhere near as.', apoio: [] },
  'Inversion – So/Neither': { q: 'Say three habits or opinions. Your partner agrees with So do I or Neither do I, or disagrees.', apoio: [] },
  'Passive Voice – Reporting Verbs': { q: 'Tell your partner something that is said or believed about your city or a famous person.', apoio: [] },
  'Relative Pronouns – Non-Defining': { q: 'Describe your hometown or a favorite singer, adding extra information with which or who between commas.', apoio: [] },
  'Inversion – Expressions with Only': { q: 'Tell your partner about something you understood only later. Use Only after... or Only when...', apoio: [] },
  'Passive Voice – Continuous': { q: 'Tell your partner what is being built, fixed or changed in your city right now.', apoio: [] },
  'Gerunds – Prepositions': { q: 'Tell your partner what you are good at, interested in and looking forward to doing.', apoio: [] },
  'Cleft Sentences': { q: 'Tell your partner the thing you like most about your school and the person who helps you most. Use It is ... who / What ... is ...', apoio: [] },
  'The + Comparative… The + Comparative': { q: 'Tell your partner three rules about life: The more you practice, the better you get.', apoio: [] },
  'Homographs': { q: 'Say a word with two meanings (like bat, key or saw). Your partner makes one sentence with each meaning.', apoio: [] },
  'Verb + Object + Infinitive': { q: 'Tell your partner who encouraged you to study English and what your family expects you to do.', apoio: [] },
  'Possessive + Gerund': { q: 'Tell your partner about a habit of a friend that you appreciate. Use I appreciate his/her + -ing.', apoio: [] },
  'Relative Pronouns – Omission': { q: 'Tell your partner about the last movie you saw and the best meal you have had, leaving out the relative pronoun.', apoio: [] },
  'Relative Clauses – Special Use of Which': { q: 'Tell your partner two things that happened this week, and comment on each one with ..., which was...', apoio: [] },
  'Confusing Words': { q: 'Choose a pair (lie/lay, rise/raise, intend/pretend). Make a true sentence about you with each word and your partner checks it.', apoio: [] },
  'Comparative + and + Comparative': { q: 'Tell your partner something that is getting more and more popular and something that is getting harder and harder.', apoio: [] },
  'Passive Voice – Two Objects': { q: 'Tell your partner about a prize, gift or piece of advice you were given.', apoio: [] },
  'Homophones': { q: 'Say a word aloud (like flour, weight or sells). Your partner says its homophone and uses both in sentences.', apoio: [] },
  'Connectors – Contrast': { q: 'Give your opinion about working from home using although, whereas and nevertheless.', apoio: [] },
  'Connectors – Cause & Result': { q: 'Tell your partner about a decision you made and its results. Use due to, as a result and therefore.', apoio: [] },
  'Connectors – Purpose & Condition': { q: 'Tell your partner what you do in order to stay healthy and provided that you have time.', apoio: [] },
  'Connectors – Addition & Sequence': { q: 'Explain how you prepare for an important test. Use first of all, furthermore and finally.', apoio: [] },
  'Phrasal Verbs – MET High-Frequency': { q: 'Tell your partner what you look into before buying something, how you get over a bad day and who keeps you posted on news.', apoio: [] },
  'Verb + Preposition': { q: 'Tell your partner what you worry about, rely on and dream of.', apoio: [] },
  'Adjective + Preposition': { q: 'Tell your partner what you are proud of, afraid of and keen on.', apoio: [] },
  'Embedded Questions': { q: 'Ask your partner polite questions about their city: Do you know where...? Could you tell me what...?', apoio: [] },
  'If vs Whether / Wh- + Infinitive': { q: 'Tell your partner about a decision you are thinking about: whether to... and where to...', apoio: [] },
  'Word Order & Parallel Structure': { q: 'Tell your partner three things you like doing on vacation, keeping the same structure: swimming, reading and sleeping.', apoio: [] },
  'Adverbs – Almost, Hardly, Still, Yet, Else': { q: 'Tell your partner something you still do, something you hardly ever do and something you haven\'t done yet this year.', apoio: [] },
  'Modal Perfects': { q: 'Tell your partner about a time something went wrong. What might have happened? What should you have done?', apoio: [] },
  'Tag Questions & Short Answers': { q: 'Guess three facts about your partner using tag questions. Your partner answers with short answers.', apoio: [] }
};
