/* QP_CONVERSA · inmediato3 (ampliado em 18/09/2026: 6 perguntas por ponto). O "Agora vocês" do modo
 * professor: conversa em duplas por ponto gramatical, em dois trios. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['inmediato3'] = {
  "La Forma Impersonal \"Uno\"": { perguntas: [
    {"q":"Cuéntale a tu pareja qué hace uno cuando se muda a una ciudad nueva.","apoio":[]},
    {"q":"¿Qué hace uno cuando no puede dormir?","apoio":[]},
    {"q":"¿Cuándo se da cuenta uno de que necesita vacaciones?","apoio":[]},
    {"q":"Cuando uno viaja solo, ¿qué debe llevar siempre?","apoio":[]},
    {"q":"¿Uno aprende más en clase o viendo series? ¿Por qué?","apoio":[]},
    {"q":"Cuando uno empieza un trabajo nuevo, ¿qué es lo más difícil?","apoio":[]},
  ] },
  "Indicativo vs Subjuntivo": { perguntas: [
    {"q":"Dile a tu pareja algo que crees sobre el futuro de la tecnología y algo que no crees que pase.","apoio":[]},
    {"q":"¿Crees que las clases por internet son tan buenas como las presenciales?","apoio":[]},
    {"q":"¿Es verdad que los brasileños llegan tarde a todo? ¿Por qué?","apoio":[]},
    {"q":"¿Te parece bien que los estudiantes usen el celular en clase?","apoio":[]},
    {"q":"¿Es posible que vivas en otro país algún día?","apoio":[]},
    {"q":"Cuéntale a tu pareja algo que sabes que es cierto y algo que dudas que sea cierto.","apoio":[]},
  ] },
  "Aunque + Indicativo / Subjuntivo": { perguntas: [
    {"q":"Cuéntale a tu pareja algo que haces aunque no te guste y algo que harás aunque sea difícil.","apoio":[]},
    {"q":"¿Qué comida comes aunque sabes que no es sana?","apoio":[]},
    {"q":"¿Irías a un concierto aunque la entrada fuera muy cara?","apoio":[]},
    {"q":"Aunque llueva este fin de semana, ¿qué vas a hacer?","apoio":[]},
    {"q":"¿Estudias aunque estés cansado? ¿Cómo lo consigues?","apoio":[]},
    {"q":"¿Qué harías aunque tus amigos no quisieran acompañarte?","apoio":[]},
  ] },
  "Perífrasis Verbales": { perguntas: [
    {"q":"Cuéntale a tu pareja qué dejaste de hacer, qué volviste a hacer y qué empezaste a hacer este año.","apoio":[]},
    {"q":"¿Qué estás a punto de terminar este mes?","apoio":[]},
    {"q":"¿Qué deberías dejar de hacer para dormir mejor?","apoio":[]},
    {"q":"¿Qué hábito has vuelto a practicar después de mucho tiempo?","apoio":[]},
    {"q":"¿Qué tarea tienes que ponerte a hacer hoy?","apoio":[]},
    {"q":"¿Qué sueles hacer los viernes por la noche?","apoio":[]},
  ] },
  "El de... / El que...": { perguntas: [
    {"q":"Señala dos objetos de la clase sin nombrarlos, con \"el de...\" o \"la que...\". Tu pareja adivina cuáles son.","apoio":[]},
    {"q":"De tus profesores, ¿cuál recuerdas más: el que era más exigente o el más divertido?","apoio":[]},
    {"q":"¿Qué películas te gustan más: las de acción o las que te hacen pensar?","apoio":[]},
    {"q":"¿Qué celular prefieres: el que tienes o el de tu mejor amigo?","apoio":[]},
    {"q":"Describe a tu pareja la casa de tus sueños y compárala con la que tienes ahora.","apoio":[]},
    {"q":"¿Qué comida prefieres: la de tu casa o la de un restaurante?","apoio":[]},
  ] },
  "Pero / Sino (que)": { perguntas: [
    {"q":"Tu pareja dice algo falso sobre ti y tú lo corriges con sino: \"No estudio medicina, sino derecho.\" Luego cambien.","apoio":[]},
    {"q":"Completa y explica: \"Para aprender un idioma, lo importante no es la gramática, sino...\"","apoio":[]},
    {"q":"¿Te gusta tu ciudad? Di algo bueno, pero también algo que no te gusta.","apoio":[]},
    {"q":"Cuéntale a tu pareja un plan que no hiciste, sino que cambiaste por otro.","apoio":[]},
    {"q":"¿Qué deporte no solo es divertido, sino también bueno para la salud?","apoio":[]},
    {"q":"Di algo que parece fácil pero es difícil, y explica por qué.","apoio":[]},
  ] },
  "Superlativo": { perguntas: [
    {"q":"Cuéntale a tu pareja cuál fue el viaje más interesante de tu vida y la comida más rara que has probado.","apoio":[]},
    {"q":"¿Cuál es el lugar más bonito de tu ciudad?","apoio":[]},
    {"q":"¿Quién es la persona más divertida de tu familia?","apoio":[]},
    {"q":"¿Cuál fue el día más feliz de tu último año?","apoio":[]},
    {"q":"¿Qué tarea de la escuela o del trabajo es la más aburrida para ti?","apoio":[]},
    {"q":"¿Cuál es la canción más escuchada de tu celular?","apoio":[]},
  ] },
  "SE Impersonal (avanzado)": { perguntas: [
    {"q":"Explícale a tu pareja cómo se vive en tu ciudad: qué se hace los domingos y qué no se permite.","apoio":[]},
    {"q":"¿Cómo se celebra un cumpleaños en tu familia?","apoio":[]},
    {"q":"¿Qué se vende en la feria de tu barrio?","apoio":[]},
    {"q":"¿Qué se debe hacer para aprobar un examen difícil?","apoio":[]},
    {"q":"¿Cómo se consigue un buen trabajo en tu ciudad?","apoio":[]},
    {"q":"¿Qué se alquila mucho en tu ciudad en las vacaciones?","apoio":[]},
  ] },
  "Pretérito Imperfecto de Subjuntivo": { perguntas: [
    {"q":"Cuéntale a tu pareja qué te pedían tus profesores en la escuela y qué querías que cambiara.","apoio":[]},
    {"q":"¿Qué querían tus padres que estudiaras?","apoio":[]},
    {"q":"¿Qué te molestaba que hicieran tus hermanos o amigos cuando eras niño?","apoio":[]},
    {"q":"¿Qué te recomendó alguien que hicieras y te ayudó mucho?","apoio":[]},
    {"q":"¿Qué esperabas que pasara en tu último viaje?","apoio":[]},
    {"q":"¿Qué te gustaría que tuviera tu barrio?","apoio":[]},
  ] },
  "Si + Pretérito Imperfecto de Subjuntivo + Condicional": { perguntas: [
    {"q":"Pregúntale a tu pareja: Si pudieras vivir un año en otro país, ¿cuál elegirías y por qué?","apoio":[]},
    {"q":"Si tuvieras un día libre mañana, ¿qué harías?","apoio":[]},
    {"q":"Si pudieras cambiar algo de tu escuela o de tu trabajo, ¿qué cambiarías?","apoio":[]},
    {"q":"Si fueras famoso por un día, ¿qué harías?","apoio":[]},
    {"q":"Si ganaras un viaje a España, ¿qué ciudad visitarías?","apoio":[]},
    {"q":"Si pudieras hablar con un personaje histórico, ¿a quién elegirías?","apoio":[]},
  ] },
  "El Artículo Neutro \"Lo\"": { perguntas: [
    {"q":"Cuéntale a tu pareja lo mejor y lo peor de tu semana.","apoio":[]},
    {"q":"¿Qué es lo más difícil de aprender español?","apoio":[]},
    {"q":"¿Qué es lo que más te gusta de tu ciudad?","apoio":[]},
    {"q":"¿Qué es lo primero que haces cuando llegas a casa?","apoio":[]},
    {"q":"Para ti, ¿qué es lo importante en una amistad?","apoio":[]},
    {"q":"Cuéntale a tu pareja lo que más recuerdas de tu infancia.","apoio":[]},
  ] },
  "Oraciones Condicionales": { perguntas: [
    {"q":"Pregúntale a tu pareja qué hará si tiene tiempo libre este fin de semana y qué haría si no tuviera que trabajar.","apoio":[]},
    {"q":"Si mañana hace sol, ¿qué harás?","apoio":[]},
    {"q":"¿Qué harías si encontraras dinero en la calle?","apoio":[]},
    {"q":"Si apruebas el curso, ¿cómo lo celebrarás?","apoio":[]},
    {"q":"¿Qué pasaría si no existiera internet por una semana?","apoio":[]},
    {"q":"Si tienes un problema con un amigo, ¿cómo lo resuelves?","apoio":[]},
  ] },
  "Cuando + Subjuntivo": { perguntas: [
    {"q":"Cuéntale a tu pareja tres cosas que harás cuando termines el curso de español.","apoio":[]},
    {"q":"¿Qué harás cuando tengas vacaciones?","apoio":[]},
    {"q":"¿Dónde vivirás cuando seas mayor?","apoio":[]},
    {"q":"¿Qué comprarás cuando ahorres suficiente dinero?","apoio":[]},
    {"q":"¿A quién llamarás cuando llegues a casa hoy?","apoio":[]},
    {"q":"¿Qué aprenderás cuando tengas más tiempo libre?","apoio":[]},
  ] },
  "Futuro Compuesto": { perguntas: [
    {"q":"Dile a tu pareja qué habrás logrado para el final de este año.","apoio":[]},
    {"q":"¿Qué habrás hecho antes de cumplir treinta años?","apoio":[]},
    {"q":"Para las próximas vacaciones, ¿qué habrás terminado?","apoio":[]},
    {"q":"Tu amigo no contesta los mensajes desde ayer. ¿Qué habrá pasado?","apoio":[]},
    {"q":"Para esta noche, ¿qué cosas ya habrás hecho?","apoio":[]},
    {"q":"¿Adónde crees que habrás viajado dentro de cinco años?","apoio":[]},
  ] },
  "Demostrativos Neutros": { perguntas: [
    {"q":"Cuéntale a tu pareja una noticia reciente y pregúntale qué piensa de eso.","apoio":[]},
    {"q":"Señala algo de la clase que no sabes cómo se llama y pregunta: ¿Qué es eso?","apoio":[]},
    {"q":"¿Recuerdas aquello que pasó en tu primer día de clase? Cuéntalo.","apoio":[]},
    {"q":"Saca algo de tu mochila y pregunta: ¿Sabes para qué sirve esto?","apoio":[]},
    {"q":"Tu pareja dice: \"Voy a dejar el celular un mes.\" ¿Qué piensas de eso?","apoio":[]},
    {"q":"Cuéntale a tu pareja un recuerdo de la infancia. ¿Por qué no olvidas aquello?","apoio":[]},
  ] },
  "Localizadores (adelante / atrás...)": { perguntas: [
    {"q":"Describe a tu pareja dónde están las cosas en tu cuarto usando adelante, atrás, encima y debajo.","apoio":[]},
    {"q":"¿Qué hay más adelante en la calle de la escuela?","apoio":[]},
    {"q":"¿Te sientas adelante o atrás en el cine? ¿Por qué?","apoio":[]},
    {"q":"¿Qué hay detrás de tu casa?","apoio":[]},
    {"q":"¿Cómo te sientes cuando hablas delante de mucha gente?","apoio":[]},
    {"q":"¿Qué guardas encima del armario o debajo de la cama?","apoio":[]},
  ] },
  "Pretérito Perfecto de Subjuntivo": { perguntas: [
    {"q":"Pregúntale a tu pareja qué le alegra que haya pasado esta semana y qué le sorprende que haya pasado.","apoio":[]},
    {"q":"Cuando hayas terminado este curso, ¿qué harás?","apoio":[]},
    {"q":"¿Qué es lo mejor que te hayan regalado?","apoio":[]},
    {"q":"Di algo que no crees que tu pareja haya hecho nunca. Pregúntale si es verdad.","apoio":[]},
    {"q":"Tu amigo no vino a clase hoy. ¿Qué puede ser que le haya pasado?","apoio":[]},
    {"q":"¿Qué esperas que haya pasado en tu casa mientras estás aquí?","apoio":[]},
  ] },
  "Preposiciones (de... a / desde... hasta)": { perguntas: [
    {"q":"Cuéntale a tu pareja tu horario de la semana: de qué hora a qué hora trabajas o estudias, y desde qué día hasta qué día.","apoio":[]},
    {"q":"¿Cuánto tardas de tu casa a la escuela?","apoio":[]},
    {"q":"¿Desde cuándo hasta cuándo son tus vacaciones este año?","apoio":[]},
    {"q":"¿De qué hora a qué hora está abierto tu lugar favorito?","apoio":[]},
    {"q":"¿Hasta qué hora te quedas despierto los sábados?","apoio":[]},
    {"q":"¿Desde qué edad hasta qué edad viviste en tu primera casa?","apoio":[]},
  ] },
  "Condicional Compuesto": { perguntas: [
    {"q":"Cuéntale a tu pareja algo que habrías hecho diferente en tu último viaje o fin de semana.","apoio":[]},
    {"q":"Con más tiempo ayer, ¿qué habrías hecho?","apoio":[]},
    {"q":"Tu amigo llegó tarde a una prueba. ¿Qué habrías hecho tú?","apoio":[]},
    {"q":"¿Qué regalo te habría gustado recibir en tu último cumpleaños?","apoio":[]},
    {"q":"En tu primer día en esta escuela, ¿qué habrías hecho de otra manera?","apoio":[]},
    {"q":"¿A qué hora te habría gustado levantarte hoy?","apoio":[]},
  ] },
  "Pretérito Pluscuamperfecto de Subjuntivo": { perguntas: [
    {"q":"Cuéntale a tu pareja qué habría pasado si no hubieras empezado a estudiar español.","apoio":[]},
    {"q":"¿Qué evento te perdiste? Completa: \"Ojalá hubiera ido a...\"","apoio":[]},
    {"q":"Si hubieras nacido en otra ciudad, ¿cuál habría sido?","apoio":[]},
    {"q":"¿Qué habrías hecho si te hubieras despertado tarde hoy?","apoio":[]},
    {"q":"Si hubieras sabido algo antes, ¿qué habrías cambiado? Cuenta un ejemplo.","apoio":[]},
    {"q":"¿Qué habría pasado si hubieras perdido el autobús esta mañana?","apoio":[]},
  ] },
  "Oraciones Condicionales (avanzado)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué harías ahora si hubieras elegido otra profesión?","apoio":[]},
    {"q":"Si hubieras vivido hace cien años, ¿qué te habría gustado hacer?","apoio":[]},
    {"q":"Si hubieras estudiado español desde niño, ¿cómo sería tu vida ahora?","apoio":[]},
    {"q":"Si tuvieras que vivir sin algo que usas mucho, ¿qué sería lo más difícil?","apoio":[]},
    {"q":"Si mañana no hay clase, ¿qué harás?","apoio":[]},
    {"q":"Si hubieras conocido antes a tu mejor amigo, ¿qué habría cambiado?","apoio":[]},
  ] },
  "Verbos de Cambio": { perguntas: [
    {"q":"Cuéntale a tu pareja la última vez que te pusiste nervioso o nerviosa, y cómo alguien que admiras llegó a ser lo que es.","apoio":[]},
    {"q":"¿Qué te hace ponerte de mal humor?","apoio":[]},
    {"q":"¿Conoces a alguien que se hizo famoso en internet?","apoio":[]},
    {"q":"¿Cuándo te quedaste sin palabras por última vez?","apoio":[]},
    {"q":"¿Qué te gustaría llegar a ser dentro de diez años?","apoio":[]},
    {"q":"¿Te has vuelto más serio o más divertido con los años?","apoio":[]},
  ] },
  "Para que / A fin de que + Subjuntivo": { perguntas: [
    {"q":"Explícale a tu pareja qué haces para que tu semana sea más organizada.","apoio":[]},
    {"q":"¿Qué le dices a un amigo para que se sienta mejor?","apoio":[]},
    {"q":"¿Qué haces para que tus plantas o tu mascota estén bien?","apoio":[]},
    {"q":"¿Qué debería hacer la escuela para que los alumnos aprendan más?","apoio":[]},
    {"q":"¿Qué hacen tus padres para que tú estés bien?","apoio":[]},
    {"q":"¿Qué harías en tu barrio a fin de que fuera más seguro?","apoio":[]},
  ] },
  "Hace + Presente / Gerundio": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Cuánto tiempo hace que estudias español? ¿Y que vives en tu casa actual?","apoio":[]},
    {"q":"¿Cuánto tiempo hace que conoces a tu mejor amigo?","apoio":[]},
    {"q":"¿Hace mucho que no vas al cine?","apoio":[]},
    {"q":"¿Cuánto tiempo hace que usas el mismo celular?","apoio":[]},
    {"q":"¿Cuánto tiempo hace que no ves a un familiar que vive lejos?","apoio":[]},
    {"q":"¿Cuánto hace que tienes tu mascota o tu objeto favorito?","apoio":[]},
  ] },
  "Llevar + Gerundio": { perguntas: [
    {"q":"Cuéntale a tu pareja cuánto tiempo llevas haciendo tu actividad favorita y cómo empezaste.","apoio":[]},
    {"q":"¿Cuánto tiempo llevas estudiando en esta escuela?","apoio":[]},
    {"q":"¿Cuántos años llevas viviendo en tu barrio?","apoio":[]},
    {"q":"¿Llevas mucho tiempo esperando algo? ¿Qué es?","apoio":[]},
    {"q":"¿Cuántos días llevas sin comer dulces?","apoio":[]},
    {"q":"¿Qué serie llevas viendo más tiempo?","apoio":[]},
  ] },
  "Estilo Indirecto: Dice que...": { perguntas: [
    {"q":"Tu pareja te cuenta un plan para el fin de semana. Cuéntaselo a otra pareja con \"dice que...\".","apoio":[]},
    {"q":"Pregúntale a tu pareja su comida favorita. Luego repítelo con \"dice que\".","apoio":[]},
    {"q":"Imagina que tu madre te manda un mensaje ahora. ¿Qué dice?","apoio":[]},
    {"q":"Lee un mensaje reciente que puedas compartir y cuéntale a tu pareja qué dice.","apoio":[]},
    {"q":"¿Qué dice siempre tu profesor o tu jefe? Repítelo con \"dice que\".","apoio":[]},
    {"q":"Tu pareja te da un consejo. Repítelo con \"me dice que...\".","apoio":[]},
  ] },
  "Voz Pasiva (Ser + Participio)": { perguntas: [
    {"q":"Háblale a tu pareja de un edificio o monumento famoso de tu ciudad: cuándo fue construido y por quién fue diseñado.","apoio":[]},
    {"q":"¿Por quién fue escrito tu libro favorito?","apoio":[]},
    {"q":"¿Cuándo fue fundada tu ciudad?","apoio":[]},
    {"q":"¿Por quién fue organizada tu última fiesta de cumpleaños?","apoio":[]},
    {"q":"¿Qué película fue dirigida por alguien que admiras?","apoio":[]},
    {"q":"¿Cuándo fue construida tu escuela o tu casa?","apoio":[]},
  ] },
  "El Imperativo y los Complementos": { perguntas: [
    {"q":"Dale a tu pareja instrucciones para preparar tu bebida favorita: cómprala, mézclala, sírvela.","apoio":[]},
    {"q":"Tu pareja te pide un libro. Responde con \"tómalo\" o \"no te lo presto\".","apoio":[]},
    {"q":"Explícale a tu pareja cómo cuidar una planta: riégala, ponla al sol...","apoio":[]},
    {"q":"Tu hermano quiere contar tu secreto. ¿Qué le dices?","apoio":[]},
    {"q":"Dale instrucciones para enviar una foto: tómala, edítala, mándasela.","apoio":[]},
    {"q":"Tu pareja olvida siempre las llaves. Aconséjale con pronombres: ponlas, guárdalas.","apoio":[]},
  ] },
  "Estilo Indirecto: Dijo que...": { perguntas: [
    {"q":"Cuéntale a tu pareja algo que alguien te dijo esta semana, con \"me dijo que...\".","apoio":[]},
    {"q":"¿Qué te dijeron tus padres antes de salir hoy?","apoio":[]},
    {"q":"¿Qué te preguntó alguien ayer? Cuéntalo con \"me preguntó si...\".","apoio":[]},
    {"q":"Cuéntale a tu pareja un consejo que te dieron: \"Me dijo que...\"","apoio":[]},
    {"q":"¿Qué noticia te contó un amigo esta semana?","apoio":[]},
    {"q":"Pregúntale algo a tu pareja y cuéntale a otra pareja qué te respondió.","apoio":[]},
  ] },
  "Pronombres Relativos": { perguntas: [
    {"q":"Describe a tu pareja un lugar en el que te sientes bien y una persona con quien te gusta conversar.","apoio":[]},
    {"q":"¿Quién es la persona que más te ayuda en tus estudios?","apoio":[]},
    {"q":"Describe una película que viste y que te gustó mucho.","apoio":[]},
    {"q":"¿Cuál es el lugar donde pasaste tus mejores vacaciones?","apoio":[]},
    {"q":"¿Tienes un amigo cuya familia es muy diferente de la tuya?","apoio":[]},
    {"q":"Describe un objeto sin decir su nombre: \"Es algo que...\"","apoio":[]},
  ] },
  "El Voseo": { perguntas: [
    {"q":"Hazle a tu pareja tres preguntas con vos, como en Argentina: ¿De dónde sos? ¿Qué querés hacer hoy? Tu pareja responde también con vos.","apoio":[]},
    {"q":"Preguntale a tu pareja con vos: ¿Qué hacés los fines de semana?","apoio":[]},
    {"q":"Con vos: ¿Tenés hermanos? ¿Cómo se llaman?","apoio":[]},
    {"q":"Con vos: ¿Dónde vivís? ¿Te gusta tu barrio?","apoio":[]},
    {"q":"Dale un consejo a tu pareja con el imperativo de vos: comé, dormí, vení.","apoio":[]},
    {"q":"Con vos: ¿Qué podés hacer mejor que tu pareja?","apoio":[]},
  ] },
  "Oraciones Temporales": { perguntas: [
    {"q":"Cuéntale a tu pareja qué haces antes de salir de casa, mientras vas a clase y después de llegar.","apoio":[]},
    {"q":"¿Qué haces en cuanto llegas a casa?","apoio":[]},
    {"q":"¿Qué haces mientras esperas el autobús?","apoio":[]},
    {"q":"¿Qué harás después de que termine la clase?","apoio":[]},
    {"q":"¿Qué hacías los sábados antes de empezar este curso?","apoio":[]},
    {"q":"Cuéntale a tu pareja algo que no haces hasta que terminas tus tareas.","apoio":[]},
  ] },
  "El Diminutivo y el Aumentativo": { perguntas: [
    {"q":"Describe tu casa o tu barrio a tu pareja con diminutivos y aumentativos: un cafecito, una casita, un perrazo.","apoio":[]},
    {"q":"¿Cómo es tu mascota o la de un amigo? Usa diminutivos.","apoio":[]},
    {"q":"¿Dónde tomas un cafecito o un jugo con tus amigos?","apoio":[]},
    {"q":"Cuéntale a tu pareja un golazo o un partidazo que viste.","apoio":[]},
    {"q":"¿Tienes un apodo con diminutivo? ¿Quién te llama así?","apoio":[]},
    {"q":"¿Cuál fue el mejor fiestón al que fuiste?","apoio":[]},
  ] },
  "Contraste Condicional Simple y Compuesto": { perguntas: [
    {"q":"Dile a tu pareja qué harías hoy con más tiempo libre y qué habrías hecho ayer con más dinero.","apoio":[]},
    {"q":"Tu pareja tiene fiebre hoy. ¿Qué harías tú en su lugar?","apoio":[]},
    {"q":"Tu pareja perdió el autobús ayer. ¿Qué habrías hecho tú?","apoio":[]},
    {"q":"¿Qué comerías ahora mismo? ¿Y qué habrías comido ayer si pudieras elegir?","apoio":[]},
    {"q":"Tu amigo no estudió para la prueba. ¿Qué le dirías hoy? ¿Qué habrías hecho tú?","apoio":[]},
    {"q":"¿Qué película verías esta noche? ¿Y cuál habrías visto el sábado pasado?","apoio":[]},
  ] },
  "Preposiciones (ante / bajo / tras)": { perguntas: [
    {"q":"Cuéntale a tu pareja cómo reaccionas ante un problema en el trabajo o en los estudios y qué haces tras un día difícil.","apoio":[]},
    {"q":"¿Cómo te sientes bajo presión en un examen?","apoio":[]},
    {"q":"¿Qué haces tras recibir una buena noticia?","apoio":[]},
    {"q":"¿Cómo reaccionas ante una crítica de un amigo?","apoio":[]},
    {"q":"¿Te gusta caminar bajo la lluvia? ¿Por qué?","apoio":[]},
    {"q":"Año tras año, ¿qué tradición mantiene tu familia?","apoio":[]},
  ] },
  "Usos de \"Apenas\"": { perguntas: [
    {"q":"Cuéntale a tu pareja qué haces apenas te despiertas y algo que apenas tienes tiempo de hacer.","apoio":[]},
    {"q":"¿Qué idioma apenas hablas pero te gustaría aprender?","apoio":[]},
    {"q":"¿Qué harás apenas termine la clase de hoy?","apoio":[]},
    {"q":"¿A quién apenas ves ahora, pero veías mucho antes?","apoio":[]},
    {"q":"¿Qué comida apenas comes porque no te gusta?","apoio":[]},
    {"q":"Cuéntale a tu pareja una noche en que apenas dormiste. ¿Por qué?","apoio":[]},
  ] },
  "Conectores": { perguntas: [
    {"q":"Dale a tu pareja tu opinión sobre las redes sociales usando además, sin embargo y por lo tanto.","apoio":[]},
    {"q":"¿Te gusta estudiar de noche? Da tu opinión con \"sin embargo\".","apoio":[]},
    {"q":"¿Por qué elegiste estudiar español? Usa \"ya que\" o \"puesto que\".","apoio":[]},
    {"q":"Cuéntale a tu pareja un día malo. Usa primero, luego y al final.","apoio":[]},
    {"q":"¿Es mejor vivir en el centro o lejos? Usa \"por un lado\" y \"por otro lado\".","apoio":[]},
    {"q":"Cuenta algo que no hiciste por falta de tiempo. Usa \"por eso\" o \"así que\".","apoio":[]},
  ] },
  "Perífrasis Verbales (andar / ir + gerundio, acabar de...)": { perguntas: [
    {"q":"Cuéntale a tu pareja algo que acabas de hacer, algo que andas buscando y algo que vas aprendiendo poco a poco.","apoio":[]},
    {"q":"¿Qué acabas de aprender en esta clase?","apoio":[]},
    {"q":"¿Qué música andas escuchando mucho estos días?","apoio":[]},
    {"q":"¿Qué hábito vas cambiando con el tiempo?","apoio":[]},
    {"q":"¿Sigues haciendo algo que hacías de niño?","apoio":[]},
    {"q":"¿Qué anda diciendo la gente de tu barrio últimamente?","apoio":[]},
  ] },
};
