/* QP_CONVERSA · inmediato3 (gerado em 17/09/2026). O "Agora vocês" do modo
 * professor: uma proposta em duplas por ponto gramatical. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['inmediato3'] = {
  'La Forma Impersonal "Uno"': { q: 'Cuéntale a tu pareja qué hace uno cuando se muda a una ciudad nueva.', apoio: [] },
  'Indicativo vs Subjuntivo': { q: 'Dile a tu pareja algo que crees sobre el futuro de la tecnología y algo que no crees que pase.', apoio: [] },
  'Aunque + Indicativo / Subjuntivo': { q: 'Cuéntale a tu pareja algo que haces aunque no te guste y algo que harás aunque sea difícil.', apoio: [] },
  'Perífrasis Verbales': { q: 'Cuéntale a tu pareja qué dejaste de hacer, qué volviste a hacer y qué empezaste a hacer este año.', apoio: [] },
  'El de... / El que...': { q: 'Señala dos objetos de la clase sin nombrarlos, con "el de..." o "la que...". Tu pareja adivina cuáles son.', apoio: [] },
  'Pero / Sino (que)': { q: 'Tu pareja dice algo falso sobre ti y tú lo corriges con sino: "No estudio medicina, sino derecho." Luego cambien.', apoio: [] },
  'Superlativo': { q: 'Cuéntale a tu pareja cuál fue el viaje más interesante de tu vida y la comida más rara que has probado.', apoio: [] },
  'SE Impersonal (avanzado)': { q: 'Explícale a tu pareja cómo se vive en tu ciudad: qué se hace los domingos y qué no se permite.', apoio: [] },
  'Pretérito Imperfecto de Subjuntivo': { q: 'Cuéntale a tu pareja qué te pedían tus profesores en la escuela y qué querías que cambiara.', apoio: [] },
  'Si + Pretérito Imperfecto de Subjuntivo + Condicional': { q: 'Pregúntale a tu pareja: Si pudieras vivir un año en otro país, ¿cuál elegirías y por qué?', apoio: [] },
  'El Artículo Neutro "Lo"': { q: 'Cuéntale a tu pareja lo mejor y lo peor de tu semana.', apoio: [] },
  'Oraciones Condicionales': { q: 'Pregúntale a tu pareja qué hará si tiene tiempo libre este fin de semana y qué haría si no tuviera que trabajar.', apoio: [] },
  'Cuando + Subjuntivo': { q: 'Cuéntale a tu pareja tres cosas que harás cuando termines el curso de español.', apoio: [] },
  'Futuro Compuesto': { q: 'Dile a tu pareja qué habrás logrado para el final de este año.', apoio: [] },
  'Demostrativos Neutros': { q: 'Cuéntale a tu pareja una noticia reciente y pregúntale qué piensa de eso.', apoio: [] },
  'Localizadores (adelante / atrás...)': { q: 'Describe a tu pareja dónde están las cosas en tu cuarto usando adelante, atrás, encima y debajo.', apoio: [] },
  'Pretérito Perfecto de Subjuntivo': { q: 'Pregúntale a tu pareja qué le alegra que haya pasado esta semana y qué le sorprende que haya pasado.', apoio: [] },
  'Preposiciones (de... a / desde... hasta)': { q: 'Cuéntale a tu pareja tu horario de la semana: de qué hora a qué hora trabajas o estudias, y desde qué día hasta qué día.', apoio: [] },
  'Condicional Compuesto': { q: 'Cuéntale a tu pareja algo que habrías hecho diferente en tu último viaje o fin de semana.', apoio: [] },
  'Pretérito Pluscuamperfecto de Subjuntivo': { q: 'Cuéntale a tu pareja qué habría pasado si no hubieras empezado a estudiar español.', apoio: [] },
  'Oraciones Condicionales (avanzado)': { q: 'Pregúntale a tu pareja: ¿Qué harías ahora si hubieras elegido otra profesión?', apoio: [] },
  'Verbos de Cambio': { q: 'Cuéntale a tu pareja la última vez que te pusiste nervioso o nerviosa, y cómo alguien que admiras llegó a ser lo que es.', apoio: [] },
  'Para que / A fin de que + Subjuntivo': { q: 'Explícale a tu pareja qué haces para que tu semana sea más organizada.', apoio: [] },
  'Hace + Presente / Gerundio': { q: 'Pregúntale a tu pareja: ¿Cuánto tiempo hace que estudias español? ¿Y que vives en tu casa actual?', apoio: [] },
  'Llevar + Gerundio': { q: 'Cuéntale a tu pareja cuánto tiempo llevas haciendo tu actividad favorita y cómo empezaste.', apoio: [] },
  'Estilo Indirecto: Dice que...': { q: 'Tu pareja te cuenta un plan para el fin de semana. Cuéntaselo a otra pareja con "dice que...".', apoio: [] },
  'Voz Pasiva (Ser + Participio)': { q: 'Háblale a tu pareja de un edificio o monumento famoso de tu ciudad: cuándo fue construido y por quién fue diseñado.', apoio: [] },
  'El Imperativo y los Complementos': { q: 'Dale a tu pareja instrucciones para preparar tu bebida favorita: cómprala, mézclala, sírvela.', apoio: [] },
  'Estilo Indirecto: Dijo que...': { q: 'Cuéntale a tu pareja algo que alguien te dijo esta semana, con "me dijo que...".', apoio: [] },
  'Pronombres Relativos': { q: 'Describe a tu pareja un lugar en el que te sientes bien y una persona con quien te gusta conversar.', apoio: [] },
  'El Voseo': { q: 'Hazle a tu pareja tres preguntas con vos, como en Argentina: ¿De dónde sos? ¿Qué querés hacer hoy? Tu pareja responde también con vos.', apoio: [] },
  'Oraciones Temporales': { q: 'Cuéntale a tu pareja qué haces antes de salir de casa, mientras vas a clase y después de llegar.', apoio: [] },
  'El Diminutivo y el Aumentativo': { q: 'Describe tu casa o tu barrio a tu pareja con diminutivos y aumentativos: un cafecito, una casita, un perrazo.', apoio: [] },
  'Contraste Condicional Simple y Compuesto': { q: 'Dile a tu pareja qué harías hoy con más tiempo libre y qué habrías hecho ayer con más dinero.', apoio: [] },
  'Preposiciones (ante / bajo / tras)': { q: 'Cuéntale a tu pareja cómo reaccionas ante un problema en el trabajo o en los estudios y qué haces tras un día difícil.', apoio: [] },
  'Usos de "Apenas"': { q: 'Cuéntale a tu pareja qué haces apenas te despiertas y algo que apenas tienes tiempo de hacer.', apoio: [] },
  'Conectores': { q: 'Dale a tu pareja tu opinión sobre las redes sociales usando además, sin embargo y por lo tanto.', apoio: [] },
  'Perífrasis Verbales (andar / ir + gerundio, acabar de...)': { q: 'Cuéntale a tu pareja algo que acabas de hacer, algo que andas buscando y algo que vas aprendiendo poco a poco.', apoio: [] },
};
