/* QP_CONVERSA · inmediato1 (ampliado em 18/09/2026: 6 perguntas por ponto). O "Agora vocês" do modo
 * professor: conversa em duplas por ponto gramatical, em dois trios. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['inmediato1'] = {
  "Artículos Determinados": { perguntas: [
    {"q":"Dile a tu pareja tres objetos de la clase con el, la, los o las.","apoio":["La mesa es grande y los libros son azules."]},
    {"q":"¿Cuál es tu día favorito de la semana? ¿Por qué?","apoio":["Mi día favorito es el sábado porque no tengo clase."]},
    {"q":"¿Te gustan los lunes?","apoio":["Sí, me gustan los lunes.","No, no me gustan los lunes."]},
    {"q":"¿Dónde están las llaves de tu casa ahora?","apoio":["Las llaves están en..."]},
    {"q":"¿Cuál es el lugar favorito de tu ciudad?","apoio":["Mi lugar favorito es el parque del..."]},
    {"q":"¿Dónde compras el pan y la fruta?","apoio":["Compro el pan en la panadería y la fruta en el mercado."]},
  ] },
  "Masculino / Femenino": { perguntas: [
    {"q":"Di una profesión en masculino y tu pareja la dice en femenino. Luego cambien.","apoio":["El profesor... la profesora."]},
    {"q":"¿Tienes un amigo o una amiga en esta clase? ¿Cómo se llama?","apoio":["Mi amiga se llama... y es..."]},
    {"q":"¿Tu profesor favorito es hombre o mujer? ¿Cómo se llama?","apoio":["Mi profesora favorita se llama Carla."]},
    {"q":"¿Tienes gato o gata? ¿Perro o perra?","apoio":["Sí, tengo una gata negra.","No, no tengo gato ni perro."]},
    {"q":"¿Qué profesión tienen las personas de tu familia?","apoio":["Mi padre es cocinero y mi madre es enfermera."]},
    {"q":"¿Tienes un vecino o una vecina simpática? ¿Cómo es?","apoio":["Mi vecina es simpática y..."]},
  ] },
  "Singular / Plural": { perguntas: [
    {"q":"Di un objeto de tu mochila en singular y tu pareja lo dice en plural.","apoio":["Un lápiz... dos lápices."]},
    {"q":"¿Cuántos hermanos o hermanas tienes?","apoio":["Tengo dos hermanos y una hermana."]},
    {"q":"¿Cuántas clases tienes por semana?","apoio":["Tengo... clases por semana."]},
    {"q":"¿Tienes animales en casa?","apoio":["Sí, tengo dos perros.","No, no tengo animales."]},
    {"q":"¿Cuántos relojes o celulares hay en tu casa?","apoio":["En mi casa hay cuatro celulares y dos relojes."]},
    {"q":"¿Qué frutas comes en la semana?","apoio":["Como plátanos, naranjas y..."]},
  ] },
  "Interrogativos": { perguntas: [
    {"q":"Hazle a tu pareja tres preguntas: ¿Cómo te llamas? ¿Dónde vives? ¿Cuántos años tienes?","apoio":["Me llamo..., vivo en... y tengo... años."]},
    {"q":"¿Cuándo es tu cumpleaños?","apoio":["Mi cumpleaños es el diez de mayo."]},
    {"q":"¿Con quién vives?","apoio":["Vivo con..."]},
    {"q":"¿Cuál es tu color favorito? ¿Por qué?","apoio":["Mi color favorito es el verde porque..."]},
    {"q":"¿Quién es tu cantante favorito?","apoio":["Mi cantante favorita es Anitta."]},
    {"q":"¿Cuántas personas hay en tu familia?","apoio":["En mi familia hay... personas."]},
  ] },
  "Presente de Indicativo (-ar)": { perguntas: [
    {"q":"Cuéntale a tu pareja tres cosas que haces por la tarde: estudiar, trabajar, escuchar música...","apoio":["Por la tarde estudio inglés y escucho música."]},
    {"q":"¿Trabajas o estudias?","apoio":["Trabajo en una tienda.","Estudio en el colegio."]},
    {"q":"¿Cuántas horas estudias por día?","apoio":["Estudio... horas por día."]},
    {"q":"¿Cocinas en casa?","apoio":["Sí, cocino arroz y frijoles.","No, no cocino nunca."]},
    {"q":"¿Qué música escuchas en el autobús o en el coche?","apoio":["Escucho... porque..."]},
    {"q":"¿Con quién hablas por teléfono todos los días?","apoio":["Hablo con mi madre todos los días."]},
  ] },
  "Presente de Indicativo (ser / llamarse)": { perguntas: [
    {"q":"Preséntate a tu pareja: di tu nombre, de dónde eres y cómo eres.","apoio":["Me llamo..., soy de... y soy...."]},
    {"q":"¿Cómo se llama tu mejor amigo o amiga? ¿Cómo es?","apoio":["Mi mejor amiga se llama Ana y es muy alegre."]},
    {"q":"¿Eres de esta ciudad?","apoio":["Sí, soy de aquí.","No, soy de São Paulo."]},
    {"q":"¿Cómo se llama tu barrio?","apoio":["Mi barrio se llama..."]},
    {"q":"¿De dónde es tu familia?","apoio":["Mi familia es de Minas Gerais."]},
    {"q":"¿Cómo eres tú: tímido o hablador?","apoio":["Soy un poco tímida.","Soy muy hablador."]},
  ] },
  "Demostrativos": { perguntas: [
    {"q":"Señala cosas de la clase y pregúntale a tu pareja: ¿Qué es esto? ¿De quién es ese libro?","apoio":["Esto es un bolígrafo.","Ese libro es de...."]},
    {"q":"Señala la ropa de tu pareja y pregunta: ¿Esta camiseta es nueva?","apoio":["Sí, esta camiseta es nueva.","No, esta camiseta es vieja."]},
    {"q":"Muéstrale una foto de tu celular a tu pareja: ¿Quién es esta persona?","apoio":["Esta es mi hermana en la playa."]},
    {"q":"Mira por la ventana: ¿Qué es aquello que está allí lejos?","apoio":["Aquello es..."]},
    {"q":"¿Qué silla prefieres, esta o aquella? ¿Por qué?","apoio":["Prefiero esta porque..."]},
    {"q":"¿De quién son estos cuadernos?","apoio":["Estos cuadernos son de Lucas."]},
  ] },
  "Presente de Indicativo (-er / -ir)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué comes en el desayuno? ¿Dónde vives?","apoio":["Como pan, bebo café y vivo en el centro."]},
    {"q":"¿Lees libros o revistas?","apoio":["Sí, leo un libro por mes.","No, no leo mucho."]},
    {"q":"¿Escribes mensajes o prefieres mandar audios?","apoio":["Escribo mensajes porque..."]},
    {"q":"¿Qué aprendes esta semana en la escuela o en el trabajo?","apoio":["Esta semana aprendo..."]},
    {"q":"¿Corres o caminas en el parque?","apoio":["Sí, corro los sábados.","No, no corro nunca."]},
    {"q":"¿Qué bebes cuando tienes calor?","apoio":["Bebo agua fría o jugo de naranja."]},
  ] },
  "Verbos Irregulares (E>IE)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿A qué hora empiezas a estudiar? ¿Qué quieres hacer hoy?","apoio":["Quiero... porque...."]},
    {"q":"¿A qué hora empieza tu día?","apoio":["Mi día empieza a las seis y media."]},
    {"q":"¿Piensas mucho en las vacaciones?","apoio":["Sí, pienso mucho en la playa.","No, no pienso mucho en eso."]},
    {"q":"¿Entiendes las películas en español sin subtítulos?","apoio":["Sí, entiendo casi todo.","No, no entiendo mucho."]},
    {"q":"¿A qué hora cierra el supermercado de tu barrio?","apoio":["El supermercado cierra a las diez."]},
    {"q":"¿Qué quieres ser en el futuro?","apoio":["Quiero ser... porque..."]},
  ] },
  "Expresiones de Tiempo y Frecuencia": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Con qué frecuencia vas al cine?","apoio":["Voy al cine una vez al mes."]},
    {"q":"¿Con qué frecuencia comes pizza?","apoio":["Como pizza... veces al mes."]},
    {"q":"¿Haces deporte todos los días?","apoio":["Sí, hago deporte todos los días.","No, casi nunca hago deporte."]},
    {"q":"¿Qué haces siempre los domingos?","apoio":["Los domingos siempre como con mi familia."]},
    {"q":"¿Qué no haces nunca?","apoio":["Yo nunca..."]},
    {"q":"¿Cuántas veces por semana vienes a la escuela?","apoio":["Vengo a la escuela dos veces por semana."]},
  ] },
  "Contracciones (al / del)": { perguntas: [
    {"q":"Cuéntale a tu pareja adónde vas después de clase y de dónde vienes hoy.","apoio":["Voy al... porque...."]},
    {"q":"¿Vas al supermercado o al mercado?","apoio":["Voy al supermercado del barrio.","Voy al mercado del centro."]},
    {"q":"¿Cuál es el mejor restaurante del barrio?","apoio":["El mejor restaurante del barrio es..."]},
    {"q":"¿Vives cerca del centro?","apoio":["Sí, vivo cerca del centro.","No, vivo lejos del centro."]},
    {"q":"¿A qué hora sales del trabajo o del colegio?","apoio":["Salgo del colegio a las..."]},
    {"q":"¿Te gusta ir al cine o al parque el domingo?","apoio":["Me gusta ir al parque con mis amigos."]},
  ] },
  "Verbos Reflexivos": { perguntas: [
    {"q":"Cuéntale a tu pareja tu rutina de la mañana: a qué hora te levantas, te duchas y te vistes.","apoio":["Me levanto a las siete y me ducho a las siete y media."]},
    {"q":"¿A qué hora te acuestas los sábados?","apoio":["Los sábados me acuesto a las..."]},
    {"q":"¿Te duchas por la mañana o por la noche?","apoio":["Me ducho por la mañana.","Me ducho por la noche."]},
    {"q":"¿Te levantas temprano el domingo?","apoio":["Sí, me levanto a las siete.","No, me levanto a las once."]},
    {"q":"¿Cómo te preparas para una fiesta?","apoio":["Me baño, me visto y me peino."]},
    {"q":"¿Te llamas igual que alguien de tu familia?","apoio":["Sí, me llamo igual que mi abuelo.","No, no me llamo como nadie."]},
  ] },
  "Verbos Irregulares (O>UE)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Cuántas horas duermes? ¿Puedes estudiar por la noche?","apoio":["Duermo... horas, porque...."]},
    {"q":"¿A qué hora vuelves a casa hoy?","apoio":["Hoy vuelvo a casa a las nueve."]},
    {"q":"¿Cuánto cuesta un helado en tu ciudad?","apoio":["Un helado cuesta... reales."]},
    {"q":"¿Puedes cocinar para tu familia?","apoio":["Sí, puedo cocinar arroz y huevos.","No, no puedo cocinar."]},
    {"q":"¿Juegas algún deporte o videojuego?","apoio":["Juego al fútbol los sábados."]},
    {"q":"¿Recuerdas el nombre de tu primera escuela?","apoio":["Sí, lo recuerdo bien.","No, no lo recuerdo."]},
  ] },
  "Verbo Ir": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Adónde vas el sábado?","apoio":["El sábado voy a... porque...."]},
    {"q":"¿Vas a la playa en las vacaciones?","apoio":["Sí, voy a la playa en enero.","No, voy a la casa de mis abuelos."]},
    {"q":"¿Con quién vas al centro comercial?","apoio":["Voy al centro comercial con mis amigos."]},
    {"q":"¿Adónde van tú y tu familia los domingos?","apoio":["Los domingos vamos a..."]},
    {"q":"¿Vas mucho al dentista?","apoio":["Sí, voy al dentista cada seis meses.","No, casi nunca voy al dentista."]},
    {"q":"¿Adónde va tu mejor amigo los fines de semana?","apoio":["Mi mejor amigo va al parque a..."]},
  ] },
  "Adjetivos": { perguntas: [
    {"q":"Describe a tu mejor amigo o amiga con tres adjetivos.","apoio":["Mi amiga es simpática, inteligente y divertida."]},
    {"q":"¿Cómo es tu casa: grande o pequeña?","apoio":["Mi casa es pequeña pero bonita."]},
    {"q":"¿Cómo es tu ciudad?","apoio":["Mi ciudad es... y..."]},
    {"q":"¿Tu película favorita es divertida o triste?","apoio":["Es muy divertida.","Es un poco triste."]},
    {"q":"¿Cómo son las personas de tu familia?","apoio":["Mis padres son trabajadores y..."]},
    {"q":"¿Tu barrio es tranquilo o ruidoso?","apoio":["Mi barrio es muy tranquilo.","Mi barrio es ruidoso."]},
  ] },
  "Posesivos (mi, tu, su...)": { perguntas: [
    {"q":"Muestra objetos a tu pareja y di de quién son: mi cuaderno, tu lápiz, su mochila.","apoio":["Este es mi cuaderno y este es tu lápiz."]},
    {"q":"¿Cómo es tu habitación?","apoio":["Mi habitación es pequeña y..."]},
    {"q":"¿De qué color es tu mochila?","apoio":["Mi mochila es negra."]},
    {"q":"¿Cuál es el plato favorito de tu familia?","apoio":["Nuestro plato favorito es la feijoada."]},
    {"q":"¿Tus amigos son de esta escuela?","apoio":["Sí, mis amigos son de aquí.","No, mis amigos son del barrio."]},
    {"q":"¿Cómo es la casa de tus abuelos?","apoio":["Su casa es... y tiene..."]},
  ] },
  "Comparación": { perguntas: [
    {"q":"Compara con tu pareja dos ciudades que conoces.","apoio":["... es más grande que... porque...."]},
    {"q":"¿Qué es más rico: la pizza o la hamburguesa?","apoio":["La pizza es más rica que la hamburguesa."]},
    {"q":"¿Eres más alto o más bajo que tu pareja?","apoio":["Soy más alto que mi compañero.","Soy más baja que mi compañera."]},
    {"q":"¿Qué es más difícil: el español o el inglés? ¿Por qué?","apoio":["El inglés es más difícil que el español porque..."]},
    {"q":"¿Tu barrio es tan tranquilo como el centro?","apoio":["Sí, es tan tranquilo como el centro.","No, es más ruidoso que el centro."]},
    {"q":"¿Qué deporte es mejor: el fútbol o el vóley?","apoio":["El vóley es mejor que el fútbol."]},
  ] },
  "Verbos Irregulares (-ZCO)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Conoces otro país? ¿Conduces?","apoio":["Sí, conozco Argentina.","No, no conduzco."]},
    {"q":"¿Conoces a alguien famoso?","apoio":["Sí, conozco a un jugador de fútbol.","No, no conozco a nadie famoso."]},
    {"q":"¿Qué ciudad de Brasil conoces bien?","apoio":["Conozco bien... porque..."]},
    {"q":"¿Ofreces ayuda a tus amigos con la tarea?","apoio":["Sí, siempre ofrezco ayuda.","No, casi nunca ofrezco ayuda."]},
    {"q":"¿Obedeces siempre a tus padres?","apoio":["Sí, obedezco casi siempre.","No, no siempre obedezco."]},
    {"q":"¿Qué traduces del español al portugués en tu día a día?","apoio":["Traduzco canciones y..."]},
  ] },
  "Localizadores": { perguntas: [
    {"q":"Esconde un objeto en la clase. Tu pareja pregunta dónde está y tú respondes.","apoio":["Está debajo de la mesa, al lado de la ventana."]},
    {"q":"¿Qué hay al lado de tu casa?","apoio":["Al lado de mi casa hay una panadería."]},
    {"q":"¿Dónde está tu celular ahora?","apoio":["Mi celular está encima de..."]},
    {"q":"¿Qué hay enfrente de la escuela?","apoio":["Enfrente de la escuela hay..."]},
    {"q":"¿Quién está a tu derecha y quién a tu izquierda?","apoio":["A mi derecha está Ana y a mi izquierda está Luis."]},
    {"q":"¿Dónde está la tele en tu sala?","apoio":["La tele está delante del sofá."]},
  ] },
  "Posesivos (mío, tuyo, suyo...)": { perguntas: [
    {"q":"Mezcla tus cosas con las de tu pareja y pregunta: ¿Es tuyo este lápiz?","apoio":["Sí, es mío.","No, no es mío. Es tuyo."]},
    {"q":"Mi mochila es negra. ¿Y la tuya?","apoio":["La mía es azul."]},
    {"q":"Mi cumpleaños es en marzo. ¿Y el tuyo?","apoio":["El mío es en..."]},
    {"q":"Mi comida favorita es la pizza. ¿Y la tuya?","apoio":["La mía es el arroz con pollo."]},
    {"q":"Mis padres son de Minas. ¿Y los tuyos?","apoio":["Los míos son de..."]},
    {"q":"Mi celular es viejo. ¿Es nuevo el tuyo?","apoio":["Sí, el mío es nuevo.","No, el mío también es viejo."]},
  ] },
  "Presente Continuo": { perguntas: [
    {"q":"Haz una mímica. Tu pareja adivina qué estás haciendo.","apoio":["¿Estás cocinando?","Sí, estoy cocinando."]},
    {"q":"¿Qué está haciendo tu familia ahora?","apoio":["Mi madre está trabajando y mi hermano..."]},
    {"q":"¿Qué serie estás viendo estos días?","apoio":["Estoy viendo una serie de..."]},
    {"q":"¿Estás estudiando para algún examen?","apoio":["Sí, estoy estudiando para matemáticas.","No, no estoy estudiando nada ahora."]},
    {"q":"Mira la clase: ¿qué están haciendo tus compañeros?","apoio":["Lucas está escribiendo y Ana está hablando."]},
    {"q":"¿Qué libro estás leyendo este mes?","apoio":["Estoy leyendo..."]},
  ] },
  "Tratamientos Formal e Informal (tú / usted)": { perguntas: [
    {"q":"Saluda a tu pareja dos veces: primero como a un amigo y después como al director de una empresa.","apoio":["¿Cómo estás?","¿Cómo está usted?"]},
    {"q":"¿Tratas de tú o de usted a tus abuelos?","apoio":["Los trato de tú.","Los trato de usted."]},
    {"q":"Pregúntale la edad a tu pareja con tú y luego con usted.","apoio":["¿Cuántos años tienes?","¿Cuántos años tiene usted?"]},
    {"q":"Pregúntale la hora a un señor en la calle. Tu pareja responde.","apoio":["Perdone, señor, ¿qué hora es?"]},
    {"q":"Pregúntale a tu pareja de dónde es, con tú y con usted.","apoio":["¿De dónde eres?","¿De dónde es usted?"]},
    {"q":"Invita a tu pareja a entrar, primero como a un amigo y después como a un cliente.","apoio":["Pasa, por favor.","Pase, por favor."]},
  ] },
  "Verbos Irregulares (-GO)": { perguntas: [
    {"q":"Cuéntale a tu pareja qué haces el domingo y qué traes a clase hoy.","apoio":["El domingo hago... porque...."]},
    {"q":"¿A qué hora sales de casa por la mañana?","apoio":["Salgo de casa a las siete."]},
    {"q":"¿Pones música para estudiar?","apoio":["Sí, pongo música tranquila.","No, no pongo música."]},
    {"q":"¿Qué dices cuando llegas a clase?","apoio":["Digo hola y..."]},
    {"q":"¿Con quién vienes a clase?","apoio":["Vengo a clase con mi hermano."]},
    {"q":"¿Oyes música en el celular o en la radio?","apoio":["Oigo música en el celular porque..."]},
  ] },
  "Números Cardinales (0–100)": { perguntas: [
    {"q":"Dile a tu pareja un número de teléfono inventado. Tu pareja lo escribe y lo repite.","apoio":["Mi número es el...."]},
    {"q":"¿Cuántos años tiene tu abuelo o tu abuela?","apoio":["Mi abuela tiene setenta y dos años."]},
    {"q":"¿Cuántos minutos necesitas para llegar a la escuela?","apoio":["Necesito... minutos."]},
    {"q":"¿Cuál es el número de tu casa o de tu apartamento?","apoio":["Vivo en el número..."]},
    {"q":"¿Cuántos grados hace hoy en tu ciudad?","apoio":["Hoy hace treinta y dos grados."]},
    {"q":"¿Cuántos libros hay en tu casa, más o menos?","apoio":["En mi casa hay unos cuarenta libros."]},
  ] },
  "Verbos Irregulares (E>I)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué pides en un restaurante?","apoio":["Pido... porque...."]},
    {"q":"¿Sigues a algún artista en las redes sociales?","apoio":["Sí, sigo a muchos cantantes.","No, no sigo a nadie."]},
    {"q":"¿Te vistes rápido o despacio por la mañana?","apoio":["Me visto muy rápido.","Me visto despacio."]},
    {"q":"¿Repites mucho la misma ropa?","apoio":["Sí, repito mi camiseta favorita.","No, casi nunca repito la ropa."]},
    {"q":"¿Qué comida sirves cuando tienes visitas?","apoio":["Cuando tengo visitas, sirvo..."]},
    {"q":"¿Qué pides de regalo en tu cumpleaños?","apoio":["Normalmente pido..."]},
  ] },
  "La Hora": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿A qué hora llegas a casa? ¿A qué hora cenas?","apoio":["Llego a las seis y ceno a las ocho."]},
    {"q":"¿Qué hora es ahora?","apoio":["Son las siete y media."]},
    {"q":"¿A qué hora empieza tu programa favorito?","apoio":["Empieza a las..."]},
    {"q":"¿A qué hora almuerzas los sábados?","apoio":["Los sábados almuerzo a la una."]},
    {"q":"¿A qué hora abre la panadería de tu barrio?","apoio":["Abre a las..."]},
    {"q":"¿A qué hora terminas el trabajo o las clases?","apoio":["Termino a las cinco y cuarto."]},
  ] },
  "La Familia": { perguntas: [
    {"q":"Cuéntale a tu pareja sobre una persona de tu familia: quién es y cómo es.","apoio":["Mi primo se llama... y es...."]},
    {"q":"¿Tienes sobrinos o primos pequeños?","apoio":["Sí, tengo dos sobrinos.","No, no tengo sobrinos."]},
    {"q":"¿Dónde viven tus abuelos?","apoio":["Mis abuelos viven en..."]},
    {"q":"¿Con quién de tu familia hablas más?","apoio":["Hablo más con mi tía porque..."]},
    {"q":"¿Tu familia es grande o pequeña?","apoio":["Mi familia es grande: tengo muchos tíos y primos."]},
    {"q":"¿Quién cocina mejor en tu familia?","apoio":["Mi abuela cocina mejor que todos."]},
  ] },
  "Números Ordinales": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿En qué piso vives? ¿Cuál es tu primera actividad del día?","apoio":["Vivo en el tercer piso."]},
    {"q":"¿Es tu primera vez estudiando español?","apoio":["Sí, es mi primera vez.","No, es la segunda vez."]},
    {"q":"¿En qué año de la escuela o de la facultad estás?","apoio":["Estoy en el... año."]},
    {"q":"¿Quién es el primer hijo de tu familia? ¿Y el segundo?","apoio":["El primer hijo es mi hermano mayor."]},
    {"q":"¿Cuál es tu segunda comida favorita?","apoio":["Mi segunda comida favorita es..."]},
    {"q":"¿En qué fila del cine te gusta sentarte?","apoio":["Me gusta sentarme en la quinta fila."]},
  ] },
  "Artículos Indeterminados": { perguntas: [
    {"q":"Dile a tu pareja tres cosas que hay en tu mochila, con un, una, unos o unas.","apoio":["En mi mochila hay un libro, una botella y unos lápices."]},
    {"q":"¿Qué hay en tu habitación?","apoio":["En mi habitación hay una cama, una mesa y..."]},
    {"q":"¿Quieres un café o un té ahora?","apoio":["Quiero un café, por favor.","Quiero un té, gracias."]},
    {"q":"¿Tienes una bicicleta?","apoio":["Sí, tengo una bicicleta roja.","No, no tengo bicicleta."]},
    {"q":"¿Qué necesitas comprar esta semana?","apoio":["Necesito unos zapatos y una camiseta."]},
    {"q":"¿Tienes un amigo de otro país?","apoio":["Sí, tengo una amiga de Chile.","No, no tengo amigos de otros países."]},
  ] },
  "Verbo Gustar": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué te gusta hacer los fines de semana?","apoio":["Me gusta... porque...."]},
    {"q":"¿Te gustan las películas de terror?","apoio":["Sí, me gustan mucho.","No, no me gustan nada."]},
    {"q":"¿Qué comida no te gusta?","apoio":["No me gusta el pescado."]},
    {"q":"¿A tu familia le gusta viajar?","apoio":["Sí, a mi familia le gusta mucho viajar.","No, a mi familia no le gusta viajar."]},
    {"q":"¿Qué música te gusta escuchar para estudiar?","apoio":["Me gusta escuchar... porque..."]},
    {"q":"¿Qué te gusta más de tu ciudad?","apoio":["Me gustan los parques y la comida."]},
  ] },
  "Acuerdo y Desacuerdo": { perguntas: [
    {"q":"Di una opinión, como \"el café es rico\" o \"el fútbol es aburrido\". Tu pareja está de acuerdo o no.","apoio":["Yo también.","Yo no, porque...."]},
    {"q":"Me gusta levantarme temprano. ¿Y a ti?","apoio":["A mí también.","A mí no."]},
    {"q":"No me gustan los lunes. ¿Y a ti?","apoio":["A mí tampoco.","A mí sí."]},
    {"q":"Yo como mucho chocolate. ¿Y tú?","apoio":["Yo también.","Yo no."]},
    {"q":"No tengo tiempo para ver series. ¿Y tú?","apoio":["Yo tampoco.","Yo sí, veo series todos los días."]},
    {"q":"Dile a tu pareja algo que te gusta de la escuela. Tu pareja responde si está de acuerdo.","apoio":["A mí también me gusta.","Pues a mí no me gusta."]},
  ] },
  "Preposiciones (desde, hasta, hacia)": { perguntas: [
    {"q":"Cuéntale a tu pareja tu horario de clases o de trabajo: desde qué hora hasta qué hora.","apoio":["Trabajo desde las ocho hasta las cinco."]},
    {"q":"¿Cuántos minutos caminas desde tu casa hasta la parada del autobús?","apoio":["Camino diez minutos desde mi casa hasta la parada."]},
    {"q":"¿Hasta qué hora ves la tele por la noche?","apoio":["Veo la tele hasta las..."]},
    {"q":"¿Desde cuándo estudias español?","apoio":["Estudio español desde..."]},
    {"q":"¿Hacia dónde está el centro desde aquí?","apoio":["El centro está hacia..."]},
    {"q":"¿Hasta qué hora duermes los domingos?","apoio":["Los domingos duermo hasta las diez."]},
  ] },
  "Hay / Tiene / Está": { perguntas: [
    {"q":"Cuéntale a tu pareja qué hay en tu barrio y dónde está tu lugar favorito.","apoio":["En mi barrio hay... y mi lugar favorito está...."]},
    {"q":"¿Hay un parque cerca de tu casa?","apoio":["Sí, hay un parque muy bonito.","No, no hay parques cerca."]},
    {"q":"¿Dónde está tu escuela o tu trabajo?","apoio":["Mi trabajo está en el centro."]},
    {"q":"¿Cuántos cuartos tiene tu casa?","apoio":["Mi casa tiene... cuartos y..."]},
    {"q":"¿De qué color tiene los ojos tu mejor amigo?","apoio":["Mi mejor amigo tiene los ojos verdes."]},
    {"q":"¿Hay mucho tráfico en tu calle?","apoio":["Sí, hay mucho tráfico.","No, hay poco tráfico."]},
  ] },
  "Medios de Transporte": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Cómo vas al trabajo o a la escuela?","apoio":["Voy en autobús porque...."]},
    {"q":"¿Vas a pie a algún lugar?","apoio":["Sí, voy a pie a la panadería.","No, voy en coche a todos lados."]},
    {"q":"¿Cómo viajas a otra ciudad: en coche, en autobús o en avión?","apoio":["Viajo en autobús porque es más barato."]},
    {"q":"¿Te gusta andar en bicicleta?","apoio":["Sí, me gusta mucho andar en bicicleta.","No, no me gusta nada."]},
    {"q":"¿Cuál es el mejor transporte en tu ciudad?","apoio":["El mejor es... porque..."]},
    {"q":"¿Tienes miedo de viajar en avión?","apoio":["Sí, tengo un poco de miedo.","No, me encanta viajar en avión."]},
  ] },
  "Imperativo Afirmativo": { perguntas: [
    {"q":"Dale a tu pareja tres instrucciones para hacer en la clase. Tu pareja las hace.","apoio":["Abre el libro, levántate y mira la ventana."]},
    {"q":"Tu pareja quiere aprender español. Dale dos consejos con imperativo.","apoio":["Escucha música en español y..."]},
    {"q":"Explica a tu pareja cómo preparar un café, paso a paso.","apoio":["Calienta el agua, pon el café en el filtro y espera."]},
    {"q":"Tu pareja llega a tu casa. Dale la bienvenida con tres imperativos.","apoio":["Pasa, siéntate y toma un vaso de agua."]},
    {"q":"Dile a tu pareja qué hacer para dormir bien.","apoio":["Apaga el celular y..."]},
    {"q":"Tu pareja está triste. Dale tres consejos.","apoio":["Llama a un amigo, sal a caminar y escucha música."]},
  ] },
  "Pronombres de Complemento Directo": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Ves la televisión? ¿Lees el periódico?","apoio":["Sí, la veo todos los días.","No, no lo leo."]},
    {"q":"¿Dónde compras tu ropa?","apoio":["La compro en el centro comercial."]},
    {"q":"¿Haces la cama todos los días?","apoio":["Sí, la hago todas las mañanas.","No, no la hago nunca."]},
    {"q":"¿Quién lava los platos en tu casa?","apoio":["Los lava mi padre."]},
    {"q":"¿Usas mucho el celular en clase?","apoio":["Sí, lo uso un poco.","No, no lo uso nunca en clase."]},
    {"q":"¿Dónde guardas tus llaves?","apoio":["Las guardo en..."]},
  ] },
  "Verbo Quedar": { perguntas: [
    {"q":"Mira la ropa de tu pareja: ¿qué le queda bien hoy?","apoio":["La camiseta te queda muy bien."]},
    {"q":"¿Qué color de ropa te queda mejor?","apoio":["El negro me queda muy bien."]},
    {"q":"¿Te queda bien la ropa de tu hermano o tu hermana?","apoio":["Sí, me queda bien.","No, me queda grande."]},
    {"q":"Mira la ropa de tu pareja y dile cómo le queda.","apoio":["Esa camiseta te queda muy bien."]},
    {"q":"¿Qué ropa te queda pequeña ahora?","apoio":["Mis pantalones viejos me quedan..."]},
    {"q":"¿Dónde queda tu restaurante favorito?","apoio":["Mi restaurante favorito queda en..."]},
  ] },
  "Pretérito Perfecto Compuesto": { perguntas: [
    {"q":"Cuéntale a tu pareja tres cosas que has hecho hoy.","apoio":["Hoy he desayunado, he trabajado y he venido a clase."]},
    {"q":"¿Has visto una película buena este mes?","apoio":["Sí, he visto una película muy divertida.","No, no he visto ninguna."]},
    {"q":"¿Has estado en otro país?","apoio":["Sí, he estado en Argentina.","No, nunca he estado en otro país."]},
    {"q":"¿Qué has comido hoy?","apoio":["Hoy he comido arroz, frijoles y..."]},
    {"q":"¿Has hablado con tus padres hoy?","apoio":["Sí, he hablado con mi madre.","No, todavía no he hablado con ellos."]},
    {"q":"¿Qué ciudades has visitado en tu vida?","apoio":["He visitado..."]},
  ] },
  "Marcadores Temporales": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué has hecho esta semana? ¿Y este año?","apoio":["Esta semana he... porque...."]},
    {"q":"¿Has ido al cine este mes?","apoio":["Sí, he ido dos veces.","No, este mes no he ido."]},
    {"q":"¿A quién has llamado hoy por teléfono?","apoio":["Hoy he llamado a mi abuela."]},
    {"q":"¿Has estudiado español alguna vez antes de este curso?","apoio":["Sí, ya he estudiado un poco.","No, nunca he estudiado español."]},
    {"q":"¿Qué has aprendido hoy en clase?","apoio":["Hoy he aprendido..."]},
    {"q":"¿Ya has almorzado hoy?","apoio":["Sí, ya he almorzado.","No, todavía no he almorzado."]},
  ] },
  "Pretérito Perfecto Simple": { perguntas: [
    {"q":"Cuéntale a tu pareja tres cosas que hiciste el fin de semana pasado.","apoio":["El sábado fui al cine y comí pizza."]},
    {"q":"¿Dónde naciste?","apoio":["Nací en..."]},
    {"q":"¿Viajaste en las últimas vacaciones?","apoio":["Sí, viajé a la playa.","No, me quedé en casa."]},
    {"q":"¿Qué comiste ayer en la cena?","apoio":["Ayer comí sopa y pan."]},
    {"q":"¿A qué hora llegaste a casa ayer?","apoio":["Ayer llegué a las..."]},
    {"q":"¿Viste a tus amigos el fin de semana?","apoio":["Sí, los vi el domingo.","No, no vi a nadie."]},
  ] },
  "Ir a + Infinitivo": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué vas a hacer esta noche?","apoio":["Voy a... porque...."]},
    {"q":"¿Vas a viajar en las próximas vacaciones?","apoio":["Sí, voy a viajar a Bahía.","No, voy a quedarme en casa."]},
    {"q":"¿Qué vas a comer hoy en la cena?","apoio":["Hoy voy a comer pasta con mi familia."]},
    {"q":"¿Qué vas a estudiar en el futuro?","apoio":["Voy a estudiar..."]},
    {"q":"¿Vas a ver algún partido este fin de semana?","apoio":["Sí, voy a ver el partido de Brasil.","No, no voy a ver ninguno."]},
    {"q":"¿Qué vas a hacer en tu próximo cumpleaños?","apoio":["En mi cumpleaños voy a..."]},
  ] },
  "Marcadores Temporales (pasado)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué hiciste ayer? ¿Y en las vacaciones del año pasado?","apoio":["Ayer fui al supermercado y el año pasado viajé a la playa."]},
    {"q":"¿Cuándo empezaste a estudiar español?","apoio":["Empecé en marzo de este año."]},
    {"q":"¿Qué hiciste anoche después de cenar?","apoio":["Anoche vi una serie y..."]},
    {"q":"¿Cuándo fue la última vez que fuiste a la playa?","apoio":["Fui a la playa hace dos meses."]},
    {"q":"¿Dónde estuviste el domingo pasado?","apoio":["El domingo pasado estuve en..."]},
    {"q":"¿Qué hiciste la semana pasada en tu tiempo libre?","apoio":["La semana pasada jugué al fútbol y fui a una fiesta."]},
  ] },
  "Pretérito Imperfecto de Indicativo": { perguntas: [
    {"q":"Cuéntale a tu pareja cómo era tu vida de niño o niña: dónde vivías y qué hacías.","apoio":["Cuando era niño, vivía en... y jugaba...."]},
    {"q":"¿Qué comida te gustaba de niño o de niña?","apoio":["De niño me gustaba mucho el helado."]},
    {"q":"¿Ibas a la escuela a pie o en autobús?","apoio":["Iba a pie.","Iba en autobús con mi madre."]},
    {"q":"¿Cómo era tu primera escuela?","apoio":["Mi primera escuela era pequeña y..."]},
    {"q":"¿Tenías un juguete favorito?","apoio":["Sí, tenía una pelota roja.","No, no tenía un favorito."]},
    {"q":"¿Qué dibujos animados veías en la tele?","apoio":["Veía..."]},
  ] },
  "Contraste entre Pretéritos": { perguntas: [
    {"q":"Cuéntale a tu pareja un día especial: qué tiempo hacía y qué pasó.","apoio":["Hacía sol y fui a... porque...."]},
    {"q":"¿Dónde estabas cuando conociste a tu mejor amigo?","apoio":["Estaba en la escuela cuando lo conocí."]},
    {"q":"¿Qué tiempo hacía cuando saliste de casa hoy?","apoio":["Hacía... cuando salí de casa."]},
    {"q":"¿Cómo fue tu primer día en esta escuela? ¿Cómo estabas?","apoio":["Estaba nervioso y..."]},
    {"q":"¿Qué hacías cuando alguien te llamó por última vez?","apoio":["Comía cuando me llamó mi madre."]},
    {"q":"¿Qué hora era cuando llegaste a clase hoy?","apoio":["Eran las siete cuando llegué."]},
  ] },
  "Presente de Indicativo (querer / preferir)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Prefieres la playa o la montaña? ¿Por qué?","apoio":["Prefiero... porque...."]},
    {"q":"¿Prefieres estudiar por la mañana o por la noche?","apoio":["Prefiero estudiar por la noche."]},
    {"q":"¿Quieres aprender otro idioma?","apoio":["Sí, quiero aprender francés.","No, prefiero solo el español."]},
    {"q":"¿Qué prefieres para el almuerzo: carne o pescado?","apoio":["Prefiero pescado porque es más sano."]},
    {"q":"¿Qué quieres hacer en tus próximas vacaciones?","apoio":["En las vacaciones quiero..."]},
    {"q":"¿Tu familia prefiere ver películas en casa o en el cine?","apoio":["Mi familia prefiere..."]},
  ] },
  "Números Cardinales (de 100 en adelante)": { perguntas: [
    {"q":"Dile a tu pareja cuánto cuesta algo que quieres comprar. Tu pareja escribe el número.","apoio":["Un celular cuesta mil quinientos reales."]},
    {"q":"¿En qué año nacieron tus padres?","apoio":["Mi padre nació en mil novecientos..."]},
    {"q":"¿Cuántos kilómetros hay de tu ciudad a la playa?","apoio":["Hay unos doscientos kilómetros."]},
    {"q":"¿Cuántos alumnos hay en tu escuela o colegio?","apoio":["En mi colegio hay unos ochocientos alumnos."]},
    {"q":"¿Cuánto cuestan unas zapatillas bonitas?","apoio":["Cuestan unos... reales."]},
    {"q":"¿Cuántas personas viven en tu ciudad, más o menos?","apoio":["En mi ciudad viven unas..."]},
  ] },
  "Dar Direcciones": { perguntas: [
    {"q":"Explícale a tu pareja cómo llegar de la escuela a un lugar cercano, como una panadería.","apoio":["Sigue todo recto y gira a la derecha."]},
    {"q":"Tu pareja está en la puerta de la escuela. Explícale cómo llegar a tu casa.","apoio":["Sigue por esta calle, gira a la izquierda y..."]},
    {"q":"¿Cómo llego al supermercado más cercano?","apoio":["Camina dos cuadras y cruza la calle."]},
    {"q":"Explícale a tu pareja cómo llegar al baño desde la clase.","apoio":["Sal de la clase, gira a la derecha y..."]},
    {"q":"Un turista pregunta por el centro. Respóndele con usted.","apoio":["Siga todo recto y gire a la izquierda."]},
    {"q":"¿Cómo llego a la parada de autobús desde aquí?","apoio":["Cruza la calle y camina..."]},
  ] },
  "Expresiones de Opinión": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué piensas de estudiar idiomas por internet?","apoio":["Creo que... porque...."]},
    {"q":"¿Qué te parece tu barrio para vivir?","apoio":["Me parece un barrio tranquilo y seguro."]},
    {"q":"¿Crees que el fútbol es el deporte más bonito?","apoio":["Sí, creo que es el mejor.","No, creo que el vóley es más bonito."]},
    {"q":"¿Qué opinas de las redes sociales?","apoio":["Opino que son útiles, pero..."]},
    {"q":"¿Qué te parece estudiar los sábados?","apoio":["Me parece cansado, pero útil."]},
    {"q":"Para ti, ¿cuál es la mejor serie del momento?","apoio":["Para mí, la mejor serie es..."]},
  ] },
  "Es que / Porque": { perguntas: [
    {"q":"Tu pareja te invita a salir hoy. Di que no y explica por qué con \"es que\".","apoio":["Lo siento, es que tengo que estudiar."]},
    {"q":"¿Por qué estudias español?","apoio":["Estudio español porque quiero viajar."]},
    {"q":"Llegas tarde a clase. Explica por qué con \"es que\".","apoio":["Perdón, es que perdí el autobús."]},
    {"q":"¿Por qué te gusta tu ciudad?","apoio":["Me gusta porque..."]},
    {"q":"Tu pareja te pide dinero prestado. Di que no con \"es que\".","apoio":["Lo siento, es que no tengo dinero hoy."]},
    {"q":"Tu pareja pregunta: ¿Por qué estás cansado hoy? Responde.","apoio":["Es que dormí poco.","Porque trabajé mucho ayer."]},
  ] },
  "Posición de los Pronombres de Complemento Directo": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Vas a ver la película hoy? ¿Estás haciendo la tarea?","apoio":["Sí, voy a verla esta noche.","No, no la estoy haciendo."]},
    {"q":"¿Vas a llamar a tu madre hoy?","apoio":["Sí, la voy a llamar esta noche.","No, no voy a llamarla hoy."]},
    {"q":"¿Tienes que hacer los deberes hoy?","apoio":["Sí, tengo que hacerlos.","No, ya los hice."]},
    {"q":"¿Has visto la última película de tu actor favorito?","apoio":["Sí, la he visto.","No, no la he visto todavía."]},
    {"q":"¿Quieres comprar un celular nuevo?","apoio":["Sí, quiero comprarlo este año.","No, no lo quiero cambiar."]},
    {"q":"¿Cuándo vas a visitar a tus abuelos?","apoio":["Voy a visitarlos..."]},
  ] },
  "Hacer un Pedido": { perguntas: [
    {"q":"Pídele un favor a tu pareja: ¿Me prestas tu lápiz?","apoio":["¿Me prestas tu lápiz, por favor?","Sí, claro. Toma."]},
    {"q":"¿Me prestas tu bolígrafo, por favor?","apoio":["Sí, claro, aquí tienes.","Lo siento, es que no tengo."]},
    {"q":"Pídele a tu pareja que te ayude con un ejercicio.","apoio":["¿Me puedes ayudar con este ejercicio?"]},
    {"q":"Pide a tu pareja que abra la ventana, con mucha educación.","apoio":["¿Puedes abrir la ventana, por favor?"]},
    {"q":"En una tienda: pide ver una camiseta de otro color.","apoio":["¿Me enseña la camiseta azul, por favor?"]},
    {"q":"Estás en una cafetería. Pide algo para comer y para beber.","apoio":["¿Me trae un jugo de naranja y un sándwich, por favor?"]},
  ] },
};
