/* QP_CONVERSA · inmediato2 (ampliado em 18/09/2026: 6 perguntas por ponto). O "Agora vocês" do modo
 * professor: conversa em duplas por ponto gramatical, em dois trios. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['inmediato2'] = {
  "Pronombres de Complemento Indirecto": { perguntas: [
    {"q":"Cuéntale a tu pareja qué le regalaste a alguien en su último cumpleaños.","apoio":["Le regalé... porque...."]},
    {"q":"¿Qué le pides a tu familia cuando necesitas ayuda?","apoio":[]},
    {"q":"¿Quién te enseñó a andar en bicicleta?","apoio":[]},
    {"q":"¿Qué les dices a tus amigos cuando llegan tarde?","apoio":["Les digo que..."]},
    {"q":"¿A quién le escribes más mensajes por día?","apoio":[]},
    {"q":"¿Qué te preguntan siempre en las fiestas de familia?","apoio":["Siempre me preguntan..."]},
  ] },
  "Pretérito Perfecto Simple (irregulares)": { perguntas: [
    {"q":"Cuéntale a tu pareja qué hiciste, adónde fuiste y qué tuviste que hacer la semana pasada.","apoio":[]},
    {"q":"¿Qué hiciste el último feriado?","apoio":["El último feriado fui a..."]},
    {"q":"¿Dónde estuviste el sábado por la noche?","apoio":[]},
    {"q":"¿Cuándo supiste que te gustaba el español?","apoio":["Lo supe cuando..."]},
    {"q":"¿Qué dijiste la última vez que llegaste tarde a algún lugar?","apoio":[]},
    {"q":"¿Qué trajiste hoy en tu mochila?","apoio":[]},
  ] },
  "Verbos de Valoración": { perguntas: [
    {"q":"Dile a tu pareja qué te encanta, qué te molesta y qué te parece aburrido de tu ciudad.","apoio":["Me encanta..., pero me molesta...."]},
    {"q":"¿Qué te parece la comida de la escuela o del trabajo?","apoio":[]},
    {"q":"¿Qué te aburre los domingos?","apoio":[]},
    {"q":"¿Qué te interesa más: el deporte, la música o el cine?","apoio":["Me interesa más... porque..."]},
    {"q":"¿Qué te molesta en el transporte público?","apoio":[]},
    {"q":"¿Qué les encanta hacer a tus amigos los viernes?","apoio":[]},
  ] },
  "Indefinidos": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Alguien de tu familia habla otro idioma? ¿Tienes algún plan para mañana?","apoio":[]},
    {"q":"¿Tienes algún amigo de otro país?","apoio":[]},
    {"q":"¿Hay algo que no comes nunca?","apoio":["No como nunca ningún..."]},
    {"q":"¿Conoces a alguien que habla tres idiomas?","apoio":[]},
    {"q":"¿Hay alguna comida de otro país que te encanta?","apoio":[]},
    {"q":"¿Qué haces cuando no hay nadie en casa?","apoio":["Cuando no hay nadie en casa,..."]},
  ] },
  "Pronombres CD e CI": { perguntas: [
    {"q":"Pregúntale a tu pareja qué hace con su celular, sus llaves y sus libros cuando llega a casa.","apoio":[]},
    {"q":"¿Quién te prepara el desayuno?","apoio":[]},
    {"q":"¿Dónde compras tus zapatos? ¿Los compras por internet?","apoio":["Los compro..."]},
    {"q":"¿Les prestas tu ropa a tus hermanos o amigos?","apoio":[]},
    {"q":"¿Llamas mucho a tus abuelos? ¿Cuándo los llamas?","apoio":["Los llamo..."]},
    {"q":"¿Me explicas cómo usas tu aplicación favorita?","apoio":[]},
  ] },
  "Contraste Pretérito Perfecto Simple y Compuesto": { perguntas: [
    {"q":"Cuéntale a tu pareja algo que has hecho esta semana y algo que hiciste el mes pasado.","apoio":["Esta semana he..., y el mes pasado...."]},
    {"q":"¿Has viajado este año? ¿Adónde fuiste el año pasado?","apoio":[]},
    {"q":"¿Qué has comido hoy y qué comiste ayer?","apoio":[]},
    {"q":"¿Qué película has visto últimamente? ¿Y cuál viste en el cine por última vez?","apoio":[]},
    {"q":"¿Has cambiado mucho desde el año pasado?","apoio":["Desde el año pasado he..."]},
    {"q":"¿Alguna vez has perdido algo importante? ¿Qué pasó?","apoio":["Una vez perdí..."]},
  ] },
  "Combinación de Pronombres (CI + CD)": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Quién te regaló tu objeto favorito? ¿Se lo prestarías a un amigo?","apoio":[]},
    {"q":"¿Le prestas tus apuntes a un compañero? ¿Se los prestas siempre?","apoio":[]},
    {"q":"¿Quién te explica los ejercicios difíciles? ¿Te los explica bien?","apoio":["Me los explica..."]},
    {"q":"Pídele a tu pareja su lápiz. Tu pareja responde con te lo o no te lo.","apoio":["Sí, te lo..."]},
    {"q":"¿Quién te cuenta las novedades de la familia? ¿Se las cuentas a alguien?","apoio":[]},
    {"q":"¿Qué regalo les diste a tus padres el año pasado? ¿Se lo diste en persona?","apoio":[]},
  ] },
  "Pretérito Pluscuamperfecto de Indicativo": { perguntas: [
    {"q":"Cuéntale a tu pareja algo que ya habías hecho antes de cumplir quince años.","apoio":["Antes de los quince años, ya había...."]},
    {"q":"¿Ya habías estudiado español antes de este curso?","apoio":[]},
    {"q":"Cuando llegaste hoy a clase, ¿qué cosas ya habías hecho?","apoio":[]},
    {"q":"La última vez que llegaste tarde, ¿qué había pasado?","apoio":["Cuando llegué, ya..."]},
    {"q":"¿Ya habías visitado otro estado antes de los diez años?","apoio":[]},
    {"q":"Cuenta un día en que todo salió mal. ¿Qué había pasado antes?","apoio":["Esa mañana, yo había..."]},
  ] },
  "Verbo Doler": { perguntas: [
    {"q":"Haz la mímica de un dolor. Tu pareja pregunta qué te duele y te da un consejo.","apoio":[]},
    {"q":"¿Qué te duele después de hacer ejercicio?","apoio":[]},
    {"q":"¿Qué haces cuando te duele la cabeza?","apoio":["Cuando me duele la cabeza,..."]},
    {"q":"¿Te duelen los ojos después de mucho tiempo en el celular?","apoio":[]},
    {"q":"¿A quién de tu familia le duele la espalda a menudo?","apoio":[]},
    {"q":"La última vez que fuiste al médico, ¿qué te dolía?","apoio":["La última vez me dolía..."]},
  ] },
  "Tener que / Hay que": { perguntas: [
    {"q":"Dile a tu pareja qué tienes que hacer esta semana y qué hay que hacer para aprender bien un idioma.","apoio":["Esta semana tengo que...."]},
    {"q":"¿Qué hay que hacer para tener una vida sana?","apoio":[]},
    {"q":"¿Qué tienes que hacer en casa todos los días?","apoio":[]},
    {"q":"¿Qué hay que llevar a un viaje a la playa?","apoio":[]},
    {"q":"¿Qué tuviste que hacer ayer que no te gustó?","apoio":["Ayer tuve que..."]},
    {"q":"¿Qué hay que saber para vivir bien en tu ciudad?","apoio":["Aquí hay que..."]},
  ] },
  "SE Impersonal": { perguntas: [
    {"q":"Explícale a tu pareja qué se come y qué se hace en una fiesta típica de tu región.","apoio":[]},
    {"q":"¿Cómo se prepara tu plato favorito?","apoio":["Primero se..."]},
    {"q":"¿Qué no se puede hacer en tu escuela o en tu trabajo?","apoio":[]},
    {"q":"¿Dónde se come bien y barato en tu ciudad?","apoio":[]},
    {"q":"¿Qué se necesita para ser un buen amigo?","apoio":["Se necesita..."]},
    {"q":"¿Se vive bien en tu barrio? ¿Por qué?","apoio":[]},
  ] },
  "Verbo Tocar": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿A quién le toca lavar los platos en tu casa? ¿Tocas algún instrumento?","apoio":[]},
    {"q":"¿A quién le toca elegir la película en tu casa?","apoio":[]},
    {"q":"¿Qué tarea de casa te toca a ti esta semana?","apoio":["Esta semana me toca..."]},
    {"q":"¿Alguna vez te tocó un premio en un sorteo de la escuela?","apoio":[]},
    {"q":"¿Qué instrumento te gustaría tocar? ¿Por qué?","apoio":[]},
    {"q":"En un viaje en coche con tu familia, ¿a quién le toca conducir?","apoio":["Normalmente le toca a..."]},
  ] },
  "Muy / Mucho(a)(s)": { perguntas: [
    {"q":"Describe tu barrio a tu pareja usando muy y mucho.","apoio":["Mi barrio es muy... y tiene muchos...."]},
    {"q":"¿Tienes mucho trabajo o muchas tareas esta semana?","apoio":[]},
    {"q":"¿Qué comida te gusta mucho y es muy barata?","apoio":[]},
    {"q":"¿Hay muchos parques en tu ciudad? ¿Son muy grandes?","apoio":[]},
    {"q":"¿Qué persona de tu familia habla mucho?","apoio":[]},
    {"q":"¿Qué te parece muy difícil en el español?","apoio":["Me parece muy difícil..."]},
  ] },
  "El Cuerpo Humano": { perguntas: [
    {"q":"Elige un deporte y explícale a tu pareja qué partes del cuerpo se usan más en él.","apoio":[]},
    {"q":"¿Cómo es tu mejor amigo: el pelo, los ojos, la altura?","apoio":["Mi amigo tiene el pelo..."]},
    {"q":"¿Qué ejercicio haces para las piernas o los brazos?","apoio":[]},
    {"q":"Describe a una persona famosa por el cuerpo y la cara. Tu pareja adivina quién es.","apoio":["Tiene los ojos..."]},
    {"q":"¿Con qué mano escribes? ¿Usas bien la otra?","apoio":[]},
    {"q":"¿Qué parte del cuerpo cuidas más? ¿Cómo la cuidas?","apoio":[]},
  ] },
  "Futuro Simple": { perguntas: [
    {"q":"Cuéntale a tu pareja cómo imaginas tu vida dentro de diez años.","apoio":["Dentro de diez años, viviré...."]},
    {"q":"¿Dónde pasarás las próximas vacaciones?","apoio":[]},
    {"q":"¿Qué harás el próximo fin de semana?","apoio":[]},
    {"q":"¿Cómo será tu ciudad dentro de veinte años?","apoio":["Creo que mi ciudad tendrá..."]},
    {"q":"¿Crees que hablarás bien español el año que viene?","apoio":[]},
    {"q":"¿Qué cosa nueva aprenderás este año?","apoio":[]},
  ] },
  "Condicional Simple": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué harías con un mes entero de vacaciones?","apoio":[]},
    {"q":"¿Qué país te gustaría conocer? ¿Por qué?","apoio":["Me gustaría conocer... porque..."]},
    {"q":"¿Qué comprarías con tu primer sueldo?","apoio":[]},
    {"q":"¿Con qué persona famosa cenarías? ¿Qué le preguntarías?","apoio":[]},
    {"q":"¿Qué cambiarías en tu escuela o en tu trabajo?","apoio":["Yo cambiaría..."]},
    {"q":"¿Podrías vivir sin celular una semana?","apoio":[]},
  ] },
  "Conjunciones (y/e – o/u)": { perguntas: [
    {"q":"Dile a tu pareja dos cosas que te gustan con y/e, y hazle una pregunta con o/u: ¿Duermes siete u ocho horas?","apoio":[]},
    {"q":"¿Estudias historia e inglés en la escuela? ¿Cuál te gusta más?","apoio":[]},
    {"q":"¿Tardas minutos u horas en llegar a clase?","apoio":["Tardo..."]},
    {"q":"Describe a tu mejor amigo con dos adjetivos unidos por e.","apoio":["Es divertido e..."]},
    {"q":"¿Qué tomas en el desayuno: leche, jugo u otra cosa?","apoio":[]},
    {"q":"Cuando tienes un problema, ¿hablas con tus padres u otra persona?","apoio":[]},
  ] },
  "Presente de Subjuntivo": { perguntas: [
    {"q":"Dile a tu pareja tres deseos para esta semana.","apoio":["Espero que...."]},
    {"q":"¿Qué esperas que haga tu equipo favorito este año?","apoio":[]},
    {"q":"¿Qué deseas que pase en tu ciudad?","apoio":[]},
    {"q":"Tu pareja tiene un examen mañana. ¿Qué le deseas?","apoio":["Ojalá que..."]},
    {"q":"¿Qué esperas que te regalen en tu cumpleaños?","apoio":[]},
    {"q":"Tu amigo viaja mañana. ¿Qué le dices antes de salir?","apoio":["Que tengas..."]},
  ] },
  "Introductores de Subjuntivo": { perguntas: [
    {"q":"Cuéntale a tu pareja qué te pide tu profesor o tu jefe y qué quieres que pase este año.","apoio":[]},
    {"q":"¿Qué te recomiendan tus padres que hagas?","apoio":[]},
    {"q":"¿Qué le recomiendas a un alumno nuevo en esta escuela?","apoio":["Te recomiendo que..."]},
    {"q":"¿Qué es importante que tenga un buen profesor?","apoio":[]},
    {"q":"¿Qué necesitas que cambie en tu barrio?","apoio":["Necesito que..."]},
    {"q":"¿Es necesario que los adolescentes tengan celular? ¿Por qué?","apoio":[]},
  ] },
  "Apócopes": { perguntas: [
    {"q":"Cuéntale a tu pareja cómo es un buen día y un mal día para ti, y cuál fue tu primer viaje.","apoio":[]},
    {"q":"¿Quién es un gran amigo tuyo? ¿Por qué?","apoio":[]},
    {"q":"¿Cuál es el primer lugar que visitas cuando llegas a una ciudad nueva?","apoio":[]},
    {"q":"¿Qué haces cuando tienes un mal día?","apoio":["Cuando tengo un mal día,..."]},
    {"q":"¿Qué es un buen regalo para tu madre o tu padre?","apoio":[]},
    {"q":"¿Tienes algún ídolo? ¿Qué gran cosa hizo?","apoio":["Mi ídolo es un gran..."]},
  ] },
  "Imperativo Afirmativo (irregulares)": { perguntas: [
    {"q":"Dale a tu pareja tres consejos para su primer día en un trabajo nuevo, con ven, ten, haz o sé.","apoio":["Ven temprano y...."]},
    {"q":"Tu pareja va a una entrevista de trabajo. Dale dos consejos con sé y ten.","apoio":[]},
    {"q":"Un amigo viene a tu ciudad. Dile qué hacer con ve y haz.","apoio":["Ve al centro y..."]},
    {"q":"Tu pareja quiere aprender a cocinar. Dale instrucciones con pon y haz.","apoio":[]},
    {"q":"Dile a tu pareja qué hacer para llegar temprano, con sal, ven y pon.","apoio":[]},
    {"q":"Tu hermano tiene miedo de su primer día de clase. Dale ánimo.","apoio":["Sé tú mismo y..."]},
  ] },
  "Imperativo Negativo": { perguntas: [
    {"q":"Dile a tu pareja tres cosas que no debe hacer antes de un examen.","apoio":[]},
    {"q":"¿Qué le dices a un amigo que usa el celular en el cine?","apoio":["No uses..."]},
    {"q":"Dale a tu pareja tres consejos para no llegar tarde.","apoio":[]},
    {"q":"Un turista visita Brasil. ¿Qué le dices que no haga?","apoio":[]},
    {"q":"Tu hermano pequeño está en la cocina. ¿Qué le dices que no toque?","apoio":[]},
    {"q":"Dale a tu pareja consejos para una entrevista: qué no decir ni hacer.","apoio":["No llegues..."]},
  ] },
  "Si + Presente de Indicativo": { perguntas: [
    {"q":"Pregúntale a tu pareja: ¿Qué haces si llueve el fin de semana?","apoio":["Si llueve,...."]},
    {"q":"¿Qué haces si pierdes el autobús?","apoio":[]},
    {"q":"¿Qué harás si tienes vacaciones en julio?","apoio":[]},
    {"q":"¿Qué comes si tienes mucha hambre por la noche?","apoio":[]},
    {"q":"¿Qué haces si un amigo está triste?","apoio":["Si un amigo está triste,..."]},
    {"q":"¿Adónde vas si quieres estar tranquilo?","apoio":[]},
  ] },
  "Introductores de Condicional (yo que tú...)": { perguntas: [
    {"q":"Cuéntale a tu pareja un pequeño problema. Tu pareja te da un consejo con \"yo que tú\" o \"yo en tu lugar\".","apoio":[]},
    {"q":"Tu pareja duerme mal. Dale un consejo con \"yo que tú\".","apoio":["Yo que tú,..."]},
    {"q":"Tu pareja quiere aprender a tocar la guitarra. ¿Qué harías en su lugar?","apoio":[]},
    {"q":"Tu pareja no sabe qué carrera elegir. Aconséjale.","apoio":["Yo en tu lugar,..."]},
    {"q":"Tu pareja gasta mucho dinero en ropa. ¿Qué le aconsejas?","apoio":[]},
    {"q":"Tu amigo tiene miedo de hablar en público. Aconséjale con \"yo que tú\".","apoio":[]},
  ] },
  "Conmigo / Contigo / Consigo": { perguntas: [
    {"q":"Invita a tu pareja a hacer algo el sábado. Tu pareja responde si va contigo o no, y por qué.","apoio":["¿Quieres ir conmigo a...?"]},
    {"q":"¿Quién estudia contigo para los exámenes?","apoio":[]},
    {"q":"¿Qué llevas siempre contigo cuando sales de casa?","apoio":[]},
    {"q":"¿Quién viaja siempre contigo en las vacaciones?","apoio":[]},
    {"q":"¿Alguien de tu familia habla consigo mismo? ¿Y tú?","apoio":["A veces..."]},
    {"q":"¿Quién es muy exigente consigo mismo en tu familia?","apoio":[]},
  ] },
  "Posición de los Pronombres con Imperativo": { perguntas: [
    {"q":"Pídele cosas a tu pareja (tu lápiz, tu cuaderno). Tu pareja responde con imperativo y pronombre: tómalo, dámelo, no lo toques.","apoio":[]},
    {"q":"Tu pareja tiene tu libro. Pídeselo con imperativo y pronombre.","apoio":["Dámelo..."]},
    {"q":"Un amigo no sabe si comprar unos zapatos caros. Aconséjale: cómpralos o no los compres.","apoio":[]},
    {"q":"Tu pareja tiene una foto divertida en el celular. Pídele que te la muestre.","apoio":[]},
    {"q":"Tu hermano quiere usar tu bicicleta. ¿Qué le dices?","apoio":["Úsala, pero..."]},
    {"q":"Tu pareja va a cocinar arroz. Explícale los pasos con pronombres: lávalo, ponlo...","apoio":[]},
  ] },
};
