/* QP_CONVERSA · inmediato1 (gerado em 17/09/2026). O "Agora vocês" do modo
 * professor: uma proposta em duplas por ponto gramatical. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['inmediato1'] = {
  'Artículos Determinados': { q: 'Dile a tu pareja tres objetos de la clase con el, la, los o las.', apoio: ['La mesa es grande y los libros son azules.'] },
  'Masculino / Femenino': { q: 'Di una profesión en masculino y tu pareja la dice en femenino. Luego cambien.', apoio: ['El profesor... la profesora.'] },
  'Singular / Plural': { q: 'Di un objeto de tu mochila en singular y tu pareja lo dice en plural.', apoio: ['Un lápiz... dos lápices.'] },
  'Interrogativos': { q: 'Hazle a tu pareja tres preguntas: ¿Cómo te llamas? ¿Dónde vives? ¿Cuántos años tienes?', apoio: ['Me llamo ___, vivo en ___ y tengo ___ años.'] },
  'Presente de Indicativo (-ar)': { q: 'Cuéntale a tu pareja tres cosas que haces por la tarde: estudiar, trabajar, escuchar música...', apoio: ['Por la tarde estudio inglés y escucho música.'] },
  'Presente de Indicativo (ser / llamarse)': { q: 'Preséntate a tu pareja: di tu nombre, de dónde eres y cómo eres.', apoio: ['Me llamo ___, soy de ___ y soy ___.'] },
  'Demostrativos': { q: 'Señala cosas de la clase y pregúntale a tu pareja: ¿Qué es esto? ¿De quién es ese libro?', apoio: ['Esto es un bolígrafo.', 'Ese libro es de ___.'] },
  'Presente de Indicativo (-er / -ir)': { q: 'Pregúntale a tu pareja: ¿Qué comes en el desayuno? ¿Dónde vives?', apoio: ['Como pan, bebo café y vivo en el centro.'] },
  'Verbos Irregulares (E>IE)': { q: 'Pregúntale a tu pareja: ¿A qué hora empiezas a estudiar? ¿Qué quieres hacer hoy?', apoio: ['Quiero ___ porque ___.'] },
  'Expresiones de Tiempo y Frecuencia': { q: 'Pregúntale a tu pareja: ¿Con qué frecuencia vas al cine?', apoio: ['Voy al cine una vez al mes.'] },
  'Contracciones (al / del)': { q: 'Cuéntale a tu pareja adónde vas después de clase y de dónde vienes hoy.', apoio: ['Voy al ___ porque ___.'] },
  'Verbos Reflexivos': { q: 'Cuéntale a tu pareja tu rutina de la mañana: a qué hora te levantas, te duchas y te vistes.', apoio: ['Me levanto a las siete y me ducho a las siete y media.'] },
  'Verbos Irregulares (O>UE)': { q: 'Pregúntale a tu pareja: ¿Cuántas horas duermes? ¿Puedes estudiar por la noche?', apoio: ['Duermo ___ horas, porque ___.'] },
  'Verbo Ir': { q: 'Pregúntale a tu pareja: ¿Adónde vas el sábado?', apoio: ['El sábado voy a ___ porque ___.'] },
  'Adjetivos': { q: 'Describe a tu mejor amigo o amiga con tres adjetivos.', apoio: ['Mi amiga es simpática, inteligente y divertida.'] },
  'Posesivos (mi, tu, su...)': { q: 'Muestra objetos a tu pareja y di de quién son: mi cuaderno, tu lápiz, su mochila.', apoio: ['Este es mi cuaderno y este es tu lápiz.'] },
  'Comparación': { q: 'Compara con tu pareja dos ciudades que conoces.', apoio: ['___ es más grande que ___ porque ___.'] },
  'Verbos Irregulares (-ZCO)': { q: 'Pregúntale a tu pareja: ¿Conoces otro país? ¿Conduces?', apoio: ['Sí, conozco Argentina.', 'No, no conduzco.'] },
  'Localizadores': { q: 'Esconde un objeto en la clase. Tu pareja pregunta dónde está y tú respondes.', apoio: ['Está debajo de la mesa, al lado de la ventana.'] },
  'Posesivos (mío, tuyo, suyo...)': { q: 'Mezcla tus cosas con las de tu pareja y pregunta: ¿Es tuyo este lápiz?', apoio: ['Sí, es mío.', 'No, no es mío. Es tuyo.'] },
  'Presente Continuo': { q: 'Haz una mímica. Tu pareja adivina qué estás haciendo.', apoio: ['¿Estás cocinando?', 'Sí, estoy cocinando.'] },
  'Tratamientos Formal e Informal (tú / usted)': { q: 'Saluda a tu pareja dos veces: primero como a un amigo y después como al director de una empresa.', apoio: ['¿Cómo estás?', '¿Cómo está usted?'] },
  'Verbos Irregulares (-GO)': { q: 'Cuéntale a tu pareja qué haces el domingo y qué traes a clase hoy.', apoio: ['El domingo hago ___ porque ___.'] },
  'Números Cardinales (0–100)': { q: 'Dile a tu pareja un número de teléfono inventado. Tu pareja lo escribe y lo repite.', apoio: ['Mi número es el ___.'] },
  'Verbos Irregulares (E>I)': { q: 'Pregúntale a tu pareja: ¿Qué pides en un restaurante?', apoio: ['Pido ___ porque ___.'] },
  'La Hora': { q: 'Pregúntale a tu pareja: ¿A qué hora llegas a casa? ¿A qué hora cenas?', apoio: ['Llego a las seis y ceno a las ocho.'] },
  'La Familia': { q: 'Cuéntale a tu pareja sobre una persona de tu familia: quién es y cómo es.', apoio: ['Mi primo se llama ___ y es ___.'] },
  'Números Ordinales': { q: 'Pregúntale a tu pareja: ¿En qué piso vives? ¿Cuál es tu primera actividad del día?', apoio: ['Vivo en el tercer piso.'] },
  'Artículos Indeterminados': { q: 'Dile a tu pareja tres cosas que hay en tu mochila, con un, una, unos o unas.', apoio: ['En mi mochila hay un libro, una botella y unos lápices.'] },
  'Verbo Gustar': { q: 'Pregúntale a tu pareja: ¿Qué te gusta hacer los fines de semana?', apoio: ['Me gusta ___ porque ___.'] },
  'Acuerdo y Desacuerdo': { q: 'Di una opinión, como "el café es rico" o "el fútbol es aburrido". Tu pareja está de acuerdo o no.', apoio: ['Yo también.', 'Yo no, porque ___.'] },
  'Preposiciones (desde, hasta, hacia)': { q: 'Cuéntale a tu pareja tu horario de clases o de trabajo: desde qué hora hasta qué hora.', apoio: ['Trabajo desde las ocho hasta las cinco.'] },
  'Hay / Tiene / Está': { q: 'Cuéntale a tu pareja qué hay en tu barrio y dónde está tu lugar favorito.', apoio: ['En mi barrio hay ___ y mi lugar favorito está ___.'] },
  'Medios de Transporte': { q: 'Pregúntale a tu pareja: ¿Cómo vas al trabajo o a la escuela?', apoio: ['Voy en autobús porque ___.'] },
  'Imperativo Afirmativo': { q: 'Dale a tu pareja tres instrucciones para hacer en la clase. Tu pareja las hace.', apoio: ['Abre el libro, levántate y mira la ventana.'] },
  'Pronombres de Complemento Directo': { q: 'Pregúntale a tu pareja: ¿Ves la televisión? ¿Lees el periódico?', apoio: ['Sí, la veo todos los días.', 'No, no lo leo.'] },
  'Verbo Quedar': { q: 'Pregúntale a tu pareja: ¿Dónde queda tu casa? ¿Queda lejos de la escuela?', apoio: ['Mi casa queda en el centro y queda cerca de la escuela.'] },
  'Pretérito Perfecto Compuesto': { q: 'Cuéntale a tu pareja tres cosas que has hecho hoy.', apoio: ['Hoy he desayunado, he trabajado y he venido a clase.'] },
  'Marcadores Temporales': { q: 'Pregúntale a tu pareja: ¿Qué has hecho esta semana? ¿Y este año?', apoio: ['Esta semana he ___ porque ___.'] },
  'Pretérito Perfecto Simple': { q: 'Cuéntale a tu pareja tres cosas que hiciste el fin de semana pasado.', apoio: ['El sábado fui al cine y comí pizza.'] },
  'Ir a + Infinitivo': { q: 'Pregúntale a tu pareja: ¿Qué vas a hacer esta noche?', apoio: ['Voy a ___ porque ___.'] },
  'Marcadores Temporales (pasado)': { q: 'Pregúntale a tu pareja: ¿Qué hiciste ayer? ¿Y en las vacaciones del año pasado?', apoio: ['Ayer fui al supermercado y el año pasado viajé a la playa.'] },
  'Pretérito Imperfecto de Indicativo': { q: 'Cuéntale a tu pareja cómo era tu vida de niño o niña: dónde vivías y qué hacías.', apoio: ['Cuando era niño, vivía en ___ y jugaba ___.'] },
  'Contraste entre Pretéritos': { q: 'Cuéntale a tu pareja un día especial: qué tiempo hacía y qué pasó.', apoio: ['Hacía sol y fui a ___ porque ___.'] },
  'Presente de Indicativo (querer / preferir)': { q: 'Pregúntale a tu pareja: ¿Prefieres la playa o la montaña? ¿Por qué?', apoio: ['Prefiero ___ porque ___.'] },
  'Números Cardinales (de 100 en adelante)': { q: 'Dile a tu pareja cuánto cuesta algo que quieres comprar. Tu pareja escribe el número.', apoio: ['Un celular cuesta mil quinientos reales.'] },
  'Dar Direcciones': { q: 'Explícale a tu pareja cómo llegar de la escuela a un lugar cercano, como una panadería.', apoio: ['Sigue todo recto y gira a la derecha.'] },
  'Expresiones de Opinión': { q: 'Pregúntale a tu pareja: ¿Qué piensas de estudiar idiomas por internet?', apoio: ['Creo que ___ porque ___.'] },
  'Es que / Porque': { q: 'Tu pareja te invita a salir hoy. Di que no y explica por qué con "es que".', apoio: ['Lo siento, es que tengo que estudiar.'] },
  'Posición de los Pronombres de Complemento Directo': { q: 'Pregúntale a tu pareja: ¿Vas a ver la película hoy? ¿Estás haciendo la tarea?', apoio: ['Sí, voy a verla esta noche.', 'No, no la estoy haciendo.'] },
  'Hacer un Pedido': { q: 'Jueguen al restaurante: uno es el camarero y el otro pide la comida.', apoio: ['Para mí, ___, por favor.'] },
};
