/* QP_CONVERSA · teensconnect1 (gerado em 17/09/2026). O "Agora vocês" do modo
 * professor: uma proposta em duplas por ponto gramatical. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['teensconnect1'] = {
  'Greetings & Introductions': { q: 'Say hello to your partner. Say your name and ask: What\'s your name?', apoio: ['Hi! My name is ___. Nice to meet you!'] },
  'Numbers 1–20': { q: 'Say a number from 1 to 20. Your partner says the next number.', apoio: ['My number is ___.'] },
  'Alphabet & Spelling': { q: 'Spell your name for your partner. Your partner writes it in the air.', apoio: ['My name is Ana. A-N-A.'] },
  'Classroom Commands': { q: 'Play teacher! Give your partner two classroom commands. Your partner does them.', apoio: ['Please ___ your book.'] },
  'Demonstratives: This/That/These/Those': { q: 'Point to things in the classroom. Ask your partner: What\'s this? What are those?', apoio: ['This is a ___.', 'Those are ___.'] },
  'To Be – Is/Are': { q: 'Look around the classroom. Tell your partner one thing with is and one thing with are.', apoio: ['The door is ___. The chairs are ___.'] },
  'Articles: A / An': { q: 'Say three things in the classroom with a or an. Take turns!', apoio: ['I see a ___.', 'I see an ___.'] },
  'Family & Jobs': { q: 'Tell your partner about one person you know and his or her job.', apoio: ['My ___ is a ___.'] },
  'Personal Pronouns': { q: 'Point to three classmates. Tell your partner who they are with he, she and they.', apoio: ['He is ___. She is ___.'] },
  'Question Word: What': { q: 'Ask your partner: What\'s your favorite color?', apoio: ['My favorite color is ___.'] },
  'School Objects': { q: 'Show your partner three school objects from your bag and say their names.', apoio: ['This is my ___.'] },
  'Feelings & Emotions': { q: 'Ask your partner: How are you today?', apoio: ['I\'m ___ today.'] },
  'To Be – Affirmative / Negative': { q: 'Tell your partner one thing you are and one thing you are not.', apoio: ['I am ___. I am not ___.'] },
  'To Be – Questions': { q: 'Ask your partner: Are you ten years old? Are you happy today?', apoio: ['Yes, I am.', 'No, I\'m not.'] },
  'Question Word: Where': { q: 'Ask your partner: Where is your pencil? Where is your bag?', apoio: ['It\'s in my ___.'] },
  'Parts of the House': { q: 'Ask your partner: What\'s your favorite part of your house?', apoio: ['My favorite part is the ___.'] },
  'Countries & Nationalities': { q: 'Ask your partner: Where are you from? What\'s your nationality?', apoio: ['I\'m from ___. I\'m ___.'] },
  'Where...From?': { q: 'Think of a famous person. Your partner asks: Where is he from? Where is she from?', apoio: ['She\'s from ___.'] },
  'Position of Adjectives': { q: 'Tell your partner about your favorite toy or object with two adjectives.', apoio: ['I have a big red ___.'] },
  'Do You Like...?': { q: 'Ask your partner: Do you like pizza? Do you like soccer?', apoio: ['Yes, I do.', 'No, I don\'t.'] },
  'Likes & Dislikes': { q: 'Tell your partner one food you like and one food you don\'t like.', apoio: ['I like ___, but I don\'t like ___.'] },
  'Prepositions: In / On (Time)': { q: 'Ask your partner: When is your birthday?', apoio: ['My birthday is in ___.'] },
  'Days, Months & Seasons': { q: 'Ask your partner: What\'s your favorite day of the week?', apoio: ['My favorite day is ___.'] },
  'Question Word: Who': { q: 'Ask your partner: Who is your best friend?', apoio: ['My best friend is ___.'] },
  'How Old Are You?': { q: 'Ask your partner: How old are you? How old is your best friend?', apoio: ['I\'m ___ years old.'] },
  'Question Word: When': { q: 'Ask your partner: When is your favorite holiday?', apoio: ['It\'s in ___.'] },
  'Imperatives': { q: 'Play Simon Says! Give your partner three commands. Your partner does them.', apoio: ['Touch your ___!'] },
  'What Time Is It?': { q: 'Draw a clock in the air. Ask your partner: What time is it?', apoio: ['It\'s ___ o\'clock.'] },
  'Numbers 21–99': { q: 'Say a number from 21 to 99. Your partner writes it in the notebook.', apoio: ['My number is ___.'] },
  'Daily Routines & Chores': { q: 'Tell your partner two things you do at home every day.', apoio: ['Every day, I ___.'] },
  'Can – Ability': { q: 'Ask your partner: Can you swim? Can you dance?', apoio: ['Yes, I can.', 'No, I can\'t.'] },
  'There Is / There Are': { q: 'Tell your partner what there is in your bedroom.', apoio: ['In my bedroom, there is a ___.'] },
  'Prepositions of Location': { q: 'Hide your eraser. Your partner asks: Where is it? You answer.', apoio: ['It\'s under the ___.'] },
  'Transportation: By / On': { q: 'Ask your partner: How do you go to school?', apoio: ['I go to school by ___.'] },
  'How Do You Get To...?': { q: 'Ask your partner: How do you get to the supermarket?', apoio: ['I get there by ___.'] },
  'Places Around Town': { q: 'Tell your partner two places in your town you like.', apoio: ['I like the ___.'] },
  'Means of Transportation': { q: 'Ask your partner: What\'s your favorite means of transportation?', apoio: ['My favorite is the ___.'] },
  'Present Continuous': { q: 'Mime an action. Your partner guesses: Are you dancing? Are you swimming?', apoio: ['Yes, I am.', 'No, I\'m not.'] },
  'Possessive Adjectives': { q: 'Point to things on the desks. Tell your partner whose they are: my book, his pen, her bag.', apoio: ['This is my ___.'] },
  'Pets & Actions': { q: 'Ask your partner: Do you have a pet? What can it do?', apoio: ['Yes, I do. It can ___.', 'No, I don\'t.'] },
  'How Many': { q: 'Ask your partner: How many pencils do you have?', apoio: ['I have ___ pencils.'] },
  'Why / Because': { q: 'Ask your partner: What\'s your favorite animal? Why?', apoio: ['My favorite animal is the ___ because it\'s ___.'] },
  'Clothes': { q: 'Tell your partner what you are wearing today.', apoio: ['I\'m wearing a ___ and ___.'] },
};
