/* QP_CONVERSA · teensconnect2 (gerado em 17/09/2026). O "Agora vocês" do modo
 * professor: uma proposta em duplas por ponto gramatical. O aluno não vê. */
window.QP_CONVERSA = window.QP_CONVERSA || {};
window.QP_CONVERSA['teensconnect2'] = {
  'Can / Can\'t': { q: 'Tell your partner two things you can do and one thing you can\'t do.', apoio: ['I can ___, but I can\'t ___.'] },
  'Prepositions of Place': { q: 'Ask your partner: Where is your backpack now?', apoio: ['It\'s next to the ___.'] },
  'Greetings & Introductions': { q: 'Introduce your partner to the pair next to you.', apoio: ['This is my friend ___.'] },
  'Simple Present – Does / Doesn\'t': { q: 'Tell your partner about a friend: one thing he or she does and one thing he or she doesn\'t do on weekends.', apoio: ['My friend plays ___, but she doesn\'t ___.'] },
  'Linking Words – And / But / Or': { q: 'Ask your partner: Do you like pizza or hamburgers? And ice cream or cake?', apoio: ['I like ___ and ___, but I don\'t like ___.'] },
  'Ordering Food': { q: 'Play restaurant! One is the waiter and the other orders a meal.', apoio: ['I\'d like a ___, please.'] },
  'Food Groups': { q: 'Tell your partner two healthy foods you eat every week.', apoio: ['I eat ___ and ___.'] },
  'Simple Present – He/She/It Spelling': { q: 'Tell your partner three things your best friend does every day.', apoio: ['She goes to ___ and watches ___.'] },
  'Parts of the Body': { q: 'Play Simon Says with your partner: touch your nose, your knee, your elbow!', apoio: ['Simon says: touch your ___!'] },
  'Expressions of Disbelief': { q: 'Tell your partner something surprising, true or false. Your partner reacts.', apoio: ['No way!', 'Really? I don\'t believe it!'] },
  'Agreeing & Disagreeing': { q: 'Say an opinion, like Math is easy or Soccer is boring. Your partner agrees or disagrees.', apoio: ['I agree!', 'I don\'t agree.'] },
  'Genitive Case': { q: 'Point to things in the classroom and tell your partner whose they are.', apoio: ['That\'s ___\'s bag.'] },
  'Whose': { q: 'Put some objects on the desk. Ask your partner: Whose pen is this?', apoio: ['It\'s mine.', 'It\'s ___\'s.'] },
  'Hobbies': { q: 'Ask your partner: What\'s your favorite hobby?', apoio: ['My favorite hobby is ___.'] },
  'Should – Advice': { q: 'Say a small problem, like I\'m tired or I\'m hungry. Your partner gives you advice.', apoio: ['You should ___.'] },
  'How Often': { q: 'Ask your partner: How often do you play video games?', apoio: ['I play video games ___.'] },
  'Linking Words – So / Because': { q: 'Tell your partner why you like your favorite day of the week.', apoio: ['I like ___ because ___.'] },
  'Health Problems': { q: 'Mime a health problem. Your partner guesses: Do you have a headache?', apoio: ['Yes, I do.', 'No, I don\'t.'] },
  'Be Going To': { q: 'Ask your partner: What are you going to do this weekend?', apoio: ['I\'m going to ___.'] },
  'May – Possibility': { q: 'Tell your partner two things you may do tomorrow after school.', apoio: ['I may ___.'] },
  'Vacation Activities': { q: 'Ask your partner: What do you like to do on vacation?', apoio: ['On vacation, I like to ___.'] },
  'Numbers & the Alphabet': { q: 'Spell a word for your partner, letter by letter. Your partner says the word.', apoio: ['C-A-T... cat!'] },
  'Showing Interest & Joining In': { q: 'Tell your partner what you are going to play after class. Your partner shows interest and asks to join.', apoio: ['Cool! Can I play too?'] },
  'To Be – Past (Was/Were)': { q: 'Ask your partner: Where were you yesterday afternoon?', apoio: ['I was at ___.'] },
  'Field Trip Places': { q: 'Ask your partner: What\'s a cool place for a field trip?', apoio: ['I want to go to the ___.'] },
  'Ordinal Numbers': { q: 'Ask your partner: What grade are you in? What floor is your classroom on?', apoio: ['I\'m in the ___ grade.'] },
  'Past Continuous': { q: 'Ask your partner: What were you doing yesterday at 8 p.m.?', apoio: ['I was ___.'] },
  'Wild Animals': { q: 'Ask your partner: What\'s your favorite wild animal? Why?', apoio: ['My favorite is the ___ because ___.'] },
  'Saying You Don\'t Like': { q: 'Tell your partner a food or a game you don\'t like.', apoio: ['I don\'t like ___ very much.'] },
  'Possessive Pronouns': { q: 'Put two objects on the desk. Ask: Is this yours? Your partner answers.', apoio: ['Yes, it\'s mine.', 'No, it\'s yours.'] },
  'Holidays & Celebrations': { q: 'Ask your partner: What\'s your favorite holiday?', apoio: ['My favorite holiday is ___.'] },
  'Dates': { q: 'Ask your partner: When is your birthday?', apoio: ['It\'s on ___.'] },
  'There Was / There Were': { q: 'Tell your partner about a party you liked. What was there?', apoio: ['There was a ___.'] },
  'Places Around the City': { q: 'Tell your partner two places near your house.', apoio: ['There is a ___ near my house.'] },
  'Giving Directions': { q: 'Give your partner directions from the classroom to the door of the school.', apoio: ['Go straight and turn ___.'] },
  'Objective Pronouns': { q: 'Tell your partner about a friend and what you do with him or her.', apoio: ['I play ___ with him.'] },
  'Irregular Plural': { q: 'Say one thing and your partner says two: one mouse, two mice!', apoio: ['One child, two ___!'] },
  'School Subjects': { q: 'Ask your partner: What\'s your favorite school subject?', apoio: ['My favorite subject is ___.'] },
  'Would Rather': { q: 'Ask your partner: Would you rather play outside or play video games?', apoio: ['I\'d rather ___.'] },
  'Making Statements & Guesses': { q: 'Hide something in your hand. Your partner guesses what it is.', apoio: ['Maybe it\'s a ___.'] },
  'Describing Animals': { q: 'Describe an animal to your partner. Your partner guesses the animal.', apoio: ['It\'s ___ and it has ___.'] },
  'Ordinal Numbers – 10th to 100th': { q: 'Say an ordinal number from 10th to 100th. Your partner says the next one.', apoio: ['Twentieth... twenty-first!'] },
  'Giving Suggestions & Showing Disappointment': { q: 'Suggest a fun activity. Your partner says you can\'t do it today and shows disappointment.', apoio: ['Let\'s go to the park!', 'Oh, no! What a pity!'] },
};
